Repository education/classroom, pull requests merged in 2018-10, with the labels that each got.

#1614 [GraphQL] Set node_id on new records
  app/jobs/assignment_repo/create_github_repository_job.rb
  app/models/assignment_repo/creator.rb
  app/models/concerns/github_repoable.rb
  app/models/github_organization.rb
  app/models/github_repository.rb
  app/models/null_github_organization.rb
  app/models/null_github_repository.rb
  app/models/organization/creator.rb
  app/services/auth_hash.rb
  spec/controllers/organizations_controller_spec.rb
  spec/models/assignment_repo/creator_spec.rb
  spec/models/group_assignment_repo_spec.rb
  spec/models/organization/creator_spec.rb
  spec/support/cassettes/GroupAssignmentRepo/with_created_objects/callbacks/before_validation/success/_create_github_repository/sets_the_GitHub_database_id_and_GraphQL_node_id.json
  spec/support/cassettes/Organization_Creator/_perform/successful_creation/creates_an_Organization_with_a_webhook_id.json
  spec/support/cassettes/Organization_Creator/_perform/successful_creation/sends_an_event_to_statd.json
  spec/support/cassettes/Organization_Creator/_perform/unsucessful_creation/deletes_the_organization_if_the_repository_permissions_cannot_be_set_to_none.json
  spec/support/cassettes/Organization_Creator/_perform/unsucessful_creation/deletes_the_webhook_if_the_process_could_not_be_completed.json
  spec/support/cassettes/OrganizationsController/POST_create/will_add_an_organization_that_the_user_is_admin_of_on_GitHub.json
  spec/support/cassettes/OrganizationsController/POST_create/will_fail_to_add_an_organization_the_user_is_not_an_admin_of.json
  spec/support/cassettes/OrganizationsController/POST_create/will_not_add_an_organization_that_already_exists.json
  spec/support/cassettes/OrganizationsController/POST_create/will_redirect_the_user_to_the_setup_page.json
Labels: GraphQL

#1617 Fix Assistant Download Button Links
  app/assets/javascripts/os.js
  app/assets/stylesheets/components/assistant.scss
  app/views/pages/_download_assistant_button.html.erb
  app/views/pages/homev2.html.erb
Labels: bug :beetle:, ready for review :writing_hand:

#1619 Remove porter status job
  app/controllers/application_controller/feature_flags_dependency.rb
  app/jobs/assignment_repo/create_github_repository_job.rb
  app/jobs/assignment_repo/porter_status_job.rb
  app/jobs/repository_import_event_job.rb
  spec/jobs/assignment_repo/create_github_repository_job_spec.rb
  spec/jobs/assignment_repo/porter_status_job_spec.rb
  spec/jobs/repository_import_event_job_spec.rb
  spec/support/cassettes/AssignmentRepo_CreateGitHubRepositoryJob/successful_creation/with_repository_import_webhook_enabled/does_not_kick_off_a_cascading_porter_status_job.json
  spec/support/cassettes/AssignmentRepo_PorterStatusJob/successful_repo_creation/started_importing_starter_code/broadcasts_failure_when_porter_API_errors.json
  spec/support/cassettes/AssignmentRepo_PorterStatusJob/successful_repo_creation/started_importing_starter_code/broadcasts_failure_when_porter_status_is_error_.json
  spec/support/cassettes/AssignmentRepo_PorterStatusJob/successful_repo_creation/started_importing_starter_code/broadcasts_when_porter_status_is_complete_.json
  spec/support/cassettes/AssignmentRepo_PorterStatusJob/successful_repo_creation/started_importing_starter_code/completes_when_porter_status_is_complete_.json
  spec/support/cassettes/AssignmentRepo_PorterStatusJob/successful_repo_creation/started_importing_starter_code/destroys_assignment_repo_when_porter_API_errors.json
  spec/support/cassettes/AssignmentRepo_PorterStatusJob/successful_repo_creation/started_importing_starter_code/destroys_assignment_repo_when_porter_status_is_error_.json
  spec/support/cassettes/AssignmentRepo_PorterStatusJob/successful_repo_creation/started_importing_starter_code/fails_when_porter_API_errors.json
  spec/support/cassettes/AssignmentRepo_PorterStatusJob/successful_repo_creation/started_importing_starter_code/fails_when_porter_status_is_error_.json
  spec/support/cassettes/AssignmentRepo_PorterStatusJob/successful_repo_creation/started_importing_starter_code/kicks_off_another_porter_status_job_when_octopoller_timesout.json
  spec/support/cassettes/AssignmentRepo_PorterStatusJob/successful_repo_creation/started_importing_starter_code/logs_failure_when_porter_API_errors.json
  spec/support/cassettes/AssignmentRepo_PorterStatusJob/successful_repo_creation/started_importing_starter_code/logs_failure_when_porter_status_is_error_.json
  spec/support/cassettes/AssignmentRepo_PorterStatusJob/successful_repo_creation/started_importing_starter_code/logs_until_porter_status_is_complete_.json
  spec/support/cassettes/AssignmentRepo_PorterStatusJob/successful_repo_creation/started_importing_starter_code/makes_DELETE_request_to_GitHub_repository_associated_with_assignment_repo_when_porter_API_errors.json
  spec/support/cassettes/AssignmentRepo_PorterStatusJob/successful_repo_creation/started_importing_starter_code/makes_DELETE_request_to_GitHub_repository_associated_with_assignment_repo_when_porter_status_is_error.json
  spec/support/cassettes/AssignmentRepo_PorterStatusJob/successful_repo_creation/started_importing_starter_code/reports_failure_stat_when_porter_status_is_error_.json
  spec/support/cassettes/AssignmentRepo_PorterStatusJob/successful_repo_creation/started_importing_starter_code/reports_success_stat_when_porter_status_is_complete_.json
  spec/support/cassettes/AssignmentRepo_PorterStatusJob/successful_repo_creation/started_importing_starter_code/reports_timeout_stat_when_porter_status_job_timesout.json
  spec/support/cassettes/AssignmentRepo_PorterStatusJob/successful_repo_creation/uses_the_porter_status_queue.json
  spec/support/cassettes/RepositoryImportEventJob/with_created_assignment_repo/doesn_t_broadcast.json
  spec/support/cassettes/RepositoryImportEventJob/with_created_assignment_repo/doesn_t_change_the_invite_status.json
  spec/support/cassettes/RepositoryImportEventJob/with_created_assignment_repo/doesn_t_report_any_stats.json
  spec/support/cassettes/RepositoryImportEventJob/with_created_assignment_repo/with_source_import_cancelled/broadcasts_cancelled.json
  spec/support/cassettes/RepositoryImportEventJob/with_created_assignment_repo/with_source_import_cancelled/reports_cancelled_stat.json
  spec/support/cassettes/RepositoryImportEventJob/with_created_assignment_repo/with_source_import_cancelled/sets_invite_status_to_errored_importing_starter_code.json
  spec/support/cassettes/RepositoryImportEventJob/with_created_assignment_repo/with_source_import_failure/broadcasts_failure.json
  spec/support/cassettes/RepositoryImportEventJob/with_created_assignment_repo/with_source_import_failure/reports_failure_stat.json
  spec/support/cassettes/RepositoryImportEventJob/with_created_assignment_repo/with_source_import_failure/sets_invite_status_to_errored_importing_starter_code.json
  spec/support/cassettes/RepositoryImportEventJob/with_created_assignment_repo/with_source_import_success/broadcasts_completion.json
  spec/support/cassettes/RepositoryImportEventJob/with_created_assignment_repo/with_source_import_success/reports_success_stat.json
  spec/support/cassettes/RepositoryImportEventJob/with_created_assignment_repo/with_source_import_success/sets_invite_status_to_completed.json
Labels: enhancement :sparkles:, ready for review :writing_hand:, repository setup :package:

#1622 Fixes animation on failure
  app/assets/javascripts/setup.js
Labels: fix :hammer_and_wrench:, ready for review :writing_hand:, repository setup :package:

#1618 Actually turn off autocomplete
  app/views/stafftools/resources/index.html.erb
Labels: fix :hammer_and_wrench:, ready for review :writing_hand:

#1613 Funnel GitHub errors to user
  app/models/concerns/github_repoable.rb
  spec/jobs/group_assignment_repo/create_github_repository_job_spec.rb
Labels: enhancement :sparkles:, ready for review :writing_hand:, repository setup :package:

#1620 Report start of import
  app/jobs/assignment_repo/create_github_repository_job.rb
  app/jobs/group_assignment_repo/create_github_repository_job.rb
  spec/jobs/assignment_repo/create_github_repository_job_spec.rb
  spec/jobs/group_assignment_repo/create_github_repository_job_spec.rb
  spec/support/cassettes/AssignmentRepo_CreateGitHubRepositoryJob/successful_creation/tracks_create_fail_stat.json
  spec/support/cassettes/AssignmentRepo_CreateGitHubRepositoryJob/successful_creation/tracks_create_success_stat.json
  spec/support/cassettes/AssignmentRepo_Creator/_perform/successful_creation/tracks_create_success_stat.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/successful_creation/datadog_stats/tracks_create_success.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/successful_creation/datadog_stats/tracks_create_success_and_import_started.json
Labels: ready for review :writing_hand:, repository setup :package:

#1628 Add 'assignment_id' argument to RepositoryCreationStatusChannel
  app/assets/javascripts/setup.js
  app/channels/repository_creation_status_channel.rb
  app/controllers/assignment_invitations_controller.rb
  app/jobs/assignment_repo/create_github_repository_job.rb
  app/jobs/repository_import_event_job.rb
  app/views/assignment_invitations/setup.html.erb
  app/views/group_assignment_invitations/setup.html.erb
  spec/channels/repository_creation_status_channel_spec.rb
  spec/jobs/assignment_repo/create_github_repository_job_spec.rb
  spec/jobs/repository_import_event_job_spec.rb
Labels: fix :hammer_and_wrench:, ready for review :writing_hand:, repository setup :package:

#1642 Centralized ElasticSearch model and index lookup
  app/controllers/stafftools/resources_controller.rb
  config/initializers/inflections.rb
  lib/es_indices.rb
Labels: dependencies, ready for review :writing_hand:

#1652 Prevent duplicate AssignmentRepos
  app/models/assignment_repo.rb
  spec/models/assignment_repo_spec.rb
Labels: fix :hammer_and_wrench:, ready for review :writing_hand:, repository setup :package:

#1658 Move linting to travis
  .travis.yml
  app/controllers/orgs/rosters_controller.rb
  config/application.rb
  lib/tasks/locked_invite_status_migration.rake
Labels: No Op

#1635 First version of GraphQL in Classroom
  Gemfile
  Gemfile.lock
  app/graphql/github_classroom_schema.rb
  app/graphql/types/mutation.rb
  app/graphql/types/query.rb
  config/application.rb
  lib/docker_compose/parser.rb
  lib/tasks/query.rake
  spec/graphql/types/query_spec.rb
  spec/graphql_helper.rb
  spec/rails_helper.rb
  vendor/cache/graphql-1.8.4.gem
  vendor/cache/graphql-batch-0.3.10.gem
  vendor/cache/graphql-remote_loader-1.0.3.gem
  vendor/cache/promise.rb-0.7.4.gem
Labels: GraphQL

#1653 Centralize InviteStatus shared behavior into SetupStatus
  app/models/concerns/setup_status.rb
  app/models/group_invite_status.rb
  app/models/invite_status.rb
  spec/models/concerns/setup_status_spec.rb
  spec/models/group_invite_status_spec.rb
  spec/models/invite_status_spec.rb
Labels: ready for review :writing_hand:, repository setup :package:

#1656 Fix assignment acceptance circling
  app/controllers/assignment_invitations_controller.rb
  app/models/assignment_invitation.rb
  spec/controllers/assignment_invitations_controller_spec.rb
Labels: fix :hammer_and_wrench:, ready for review :writing_hand:, repository setup :package:

#1657 Disable assignment download button
  app/views/assignments/show.html.erb
  app/views/group_assignments/show.html.erb
  app/views/shared/_open_on_assistant_modal.html.erb
Labels: Hacktoberfest, classroom assistant :desktop_computer:, fix :hammer_and_wrench:, ready for review :writing_hand:

#1667 Order paginated requests
  app/controllers/assignments_controller.rb
  app/controllers/group_assignments_controller.rb
  app/controllers/orgs/rosters_controller.rb
Labels: fix :hammer_and_wrench:

#1671 Add order to API Calls
  app/controllers/api/assignment_repos_controller.rb
  app/controllers/api/group_assignment_repos_controller.rb
Labels: fix :hammer_and_wrench:

#1673 Fix CGI Escape on API Tokens
  app/controllers/assignments_controller.rb
  app/controllers/group_assignments_controller.rb
  app/controllers/oauth_controller.rb
  lib/message_verifier.rb
  spec/support/cassettes/OauthController/GET_authorize/generates_a_code_that_has_correct_user_id.json
  spec/support/cassettes/OauthController/GET_authorize/generates_a_code_that_is_invalid_in_5_minutes.json
  spec/support/cassettes/OauthController/GET_authorize/redirect_url_param_is_not_present/renders_404.json
  spec/support/cassettes/OauthController/GET_authorize/redirect_url_param_is_present/generates_a_code_that_has_correct_user_id.json
  spec/support/cassettes/OauthController/GET_authorize/redirect_url_param_is_present/generates_a_code_that_is_invalid_in_5_minutes.json
  spec/support/cassettes/OauthController/GET_authorize/redirect_url_param_is_present/redirects_to_redirect_url.json
  spec/support/cassettes/OauthController/GET_authorize/redirects_to_redirect_url.json
  spec/support/cassettes/OauthController/GET_authorize/redirects_to_x-github-classroom.json
  spec/support/cassettes/OauthController/flipper_is_enabled/GET_authorize/redirect_url_param_is_not_present/renders_404.json
  spec/support/cassettes/OauthController/flipper_is_enabled/GET_authorize/redirect_url_param_is_present/generates_a_code_that_has_correct_user_id.json
  spec/support/cassettes/OauthController/flipper_is_enabled/GET_authorize/redirect_url_param_is_present/generates_a_code_that_is_invalid_in_5_minutes.json
  spec/support/cassettes/OauthController/flipper_is_enabled/GET_authorize/redirect_url_param_is_present/redirects_to_redirect_url.json
Labels: fix :hammer_and_wrench:, ready for review :writing_hand:

#1248 Allow a GitHub Organization to be used by multiple Classrooms
  app/controllers/application_controller/feature_flags_dependency.rb
  app/controllers/organizations_controller.rb
  app/models/concerns/sluggable.rb
  app/models/github_organization.rb
  app/models/organization.rb
  app/models/organization/creator.rb
  app/views/organizations/_reset_and_remove_organization_modal.html.erb
  app/views/organizations/new.html.erb
  config/locales/views/organizations/en.yml
  spec/controllers/organizations_controller_spec.rb
  spec/models/organization/creator_spec.rb
  spec/models/organization_spec.rb
  spec/support/cassettes/Organization/callbacks/before_destroy/_silently_remove_organization_webhook/last_classroom_on_organization/deletes_the_webhook_from_GitHub.json
  spec/support/cassettes/Organization_Creator/_perform/successful_creation/already_created_webhook_on_GitHub_org/sets_webhook_id_to_what_it_is_already_set_on_org.json
  spec/support/cassettes/Organization_Creator/_perform/successful_creation/creates_an_Organization_with_a_webhook_id.json
  spec/support/cassettes/Organization_Creator/_perform/successful_creation/multiple_classrooms_on_same_organization/creates_a_classroom_with_the_default_title_but_incremented_id.json
  spec/support/cassettes/Organization_Creator/_perform/successful_creation/multiple_classrooms_on_same_organization/creates_a_classroom_with_the_same_webhook_id_as_the_existing_one.json
  spec/support/cassettes/Organization_Creator/_perform/successful_creation/sends_an_event_to_statd.json
  spec/support/cassettes/Organization_Creator/_perform/successful_creation/webhook_already_on_org/sets_webhook_id_from_github.json
  spec/support/cassettes/Organization_Creator/_perform/unsucessful_creation/deletes_the_organization_if_the_repository_permissions_cannot_be_set_to_none.json
  spec/support/cassettes/Organization_Creator/_perform/unsucessful_creation/deletes_the_webhook_if_the_process_could_not_be_completed.json
  spec/support/cassettes/Organization_Creator/_perform/unsucessful_creation/does_not_allow_non_admins_to_be_added.json
  spec/support/cassettes/OrganizationsController/POST_create/multiple_classrooms_per_org_flag_is_enabled/will_add_a_classroom_on_same_organization.json
  spec/support/cassettes/OrganizationsController/POST_create/multiple_classrooms_per_org_flag_not_enabled/will_not_add_an_organization_that_already_exists.json
  spec/support/cassettes/OrganizationsController/POST_create/will_add_an_organization_that_the_user_is_admin_of_on_GitHub.json
  spec/support/cassettes/OrganizationsController/POST_create/will_fail_to_add_an_organization_the_user_is_not_an_admin_of.json
  spec/support/cassettes/OrganizationsController/POST_create/will_not_add_an_organization_that_already_exists.json
  spec/support/cassettes/OrganizationsController/POST_create/will_redirect_the_user_to_the_setup_page.json
Labels: enhancement :sparkles:

#1683 Paginate groups on group_assignment_invitations_controller#show
  app/controllers/group_assignment_invitations_controller.rb
  app/views/group_assignment_invitations/_group_assignment_team.erb
  app/views/group_assignment_invitations/show.html.erb
Labels: enhancement :sparkles:, fix :hammer_and_wrench:

#1686 Validate that no emojis are in a Group's Title
  Gemfile
  Gemfile.lock
  app/models/group.rb
  lib/no_emoji_validator.rb
  spec/lib/no_emoji_validator_spec.rb
  spec/models/group_spec.rb
  vendor/cache/unicode-emoji-1.1.0.gem
Labels: enhancement :sparkles:, fix :hammer_and_wrench:
