Repository education/classroom, pull requests merged in 2018-03, with the labels that each got.

#1251 Use Docker Compose for dependencies instead of Homebrew services
  .node-version
  .travis.yml
  Brewfile
  Procfile.dev
  README.md
  bin/setup
  bin/update
  config/chewy.yml
  config/database.yml
  config/environments/development.rb
  config/initializers/02_redis.rb
  config/initializers/sidekiq.rb
  docker-compose.yml
  lib/docker_compose.rb
  lib/docker_compose/parser.rb
  lib/docker_compose/service.rb
  lib/docker_compose/services.rb
  script/bootstrap
  script/cibuild
  script/docker-services
  script/poll-for-services
  script/setup
  script/sidekiq
  script/update
  spec/support/cassettes/OAuth_scope_requirements/OAuth_dance/redirects_back_to_organizations_show.json
  spec/support/cassettes/OAuth_scope_requirements/organizations_show/authenticated_request/renders_organizations_show.json
Labels: :clock1: in progress, :muscle: enhancement

#1254 Create Membership Event Job
  app/jobs/membership_event_job.rb
  lib/github/web_hook.rb
  spec/fixtures/files/webhook_events/team_member_removed.json
  spec/jobs/membership_event_job_spec.rb
  spec/support/cassettes/MembershipEventJob/ACTION_member_removed/removes_user_from_team.json
Labels: :rocket: ready for review

#1305 Classroom's changelog #1
  app/views/shared/_header.html.erb
  app/views/shared/_invitation_header.html.erb
  config/locales/views/shared/en.yml
Labels: :clock1: in progress

#1274 Remove user from Organization
  app/jobs/organization_event_job.rb
  lib/github/web_hook.rb
  spec/fixtures/files/webhook_events/member_removed.json
  spec/jobs/organization_event_job_spec.rb
Labels: :rocket: ready for review

#1320 script/setup and script/server fix
  script/server
  script/setup
  script/update
Labels: classroom-setup

#1318 Fix jobs/organization_event_job.rb
  app/jobs/organization_event_job.rb
  spec/jobs/organization_event_job_spec.rb
Labels: :rocket: ready for review

#1326 Fix pagination for non rosters orgs
  app/controllers/group_assignments_controller.rb
Labels: :bookmark_tabs: assignments, :rocket: ready for review

#1314 Add an issue template
  .github/ISSUE_TEMPLATE.md
Labels: :rocket: ready for review

#1283 Sort assignments by title
  app/controllers/organizations_controller.rb
Labels: :rocket: ready for review

#1331 Administrators list
  app/controllers/organizations_controller.rb
  app/models/organization.rb
  app/models/user.rb
  app/views/organizations/_organization_user.html.erb
  app/views/organizations/_organization_users.html.erb
  app/views/organizations/_remove_user_modal.html.erb
  app/views/organizations/invitation.html.erb
  config/locales/views/organizations/en.yml
  config/routes.rb
  spec/controllers/organizations_controller_spec.rb
  spec/support/cassettes/OrganizationsController/PATCH_remove_user/removes_the_user_from_classroom_without_assignments.json
  spec/support/cassettes/OrganizationsController/PATCH_remove_user/removes_user_from_classroom/with_assignments.json
  spec/support/cassettes/OrganizationsController/PATCH_remove_user/removes_user_from_classroom/without_assignments.json
  spec/support/cassettes/OrganizationsController/PATCH_remove_user/returns_404/user_does_not_exist.json
  spec/support/cassettes/OrganizationsController/PATCH_remove_user/returns_404/user_is_not_an_org_owner.json
  spec/support/cassettes/OrganizationsController/PATCH_remove_user/returns_404_if_the_user_is_not_a_member_of_the_org.json
  spec/support/cassettes/OrganizationsController/PATCH_remove_user/returns_404_if_user_does_not_exist.json
Labels: :rocket: ready for review
