Repository education/classroom, pull requests merged in 2018-09, with the labels that each got.

#1538 Reduced porter status polling + added data dog event
  app/jobs/assignment_repo/porter_status_job.rb
  spec/jobs/assignment_repo/porter_status_job_spec.rb
Labels: :hammer_and_wrench: fix, create/import repo flow

#1539 Octopoller gem
  Gemfile
  Gemfile.lock
  lib/octopoller.rb
  spec/lib/octopoller_spec.rb
  vendor/cache/octopoller-0.1.0.gem
Labels: :rocket: ready for review, :sparkles: enhancement

#1541 Bump ffi to 1.9.24
  Gemfile.lock
  vendor/cache/ffi-1.9.18.gem
  vendor/cache/ffi-1.9.24.gem
Labels: :hammer_and_wrench: fix, :rocket: ready for review

#1544 Repository import event job
  app/controllers/application_controller/feature_flags_dependency.rb
  app/jobs/assignment_repo/create_github_repository_job.rb
  app/jobs/repository_import_event_job.rb
  lib/github/web_hook.rb
  spec/fixtures/files/webhook_events/repository_import_failure.json
  spec/fixtures/files/webhook_events/repository_import_success.json
  spec/jobs/assignment_repo/create_github_repository_job_spec.rb
  spec/jobs/repository_import_event_job_spec.rb
  spec/support/cassettes/AssignmentRepo_CreateGitHubRepositoryJob/failure/broadcasts_create_repo_failure.json
  spec/support/cassettes/AssignmentRepo_CreateGitHubRepositoryJob/failure/fails_and_automatically_retries.json
  spec/support/cassettes/AssignmentRepo_CreateGitHubRepositoryJob/failure/fails_and_puts_invite_status_in_state_to_retry.json
  spec/support/cassettes/AssignmentRepo_CreateGitHubRepositoryJob/failure/fails_to_create_repo_and_retries.json
  spec/support/cassettes/AssignmentRepo_CreateGitHubRepositoryJob/failure/tracks_create_fail_stat.json
  spec/support/cassettes/AssignmentRepo_CreateGitHubRepositoryJob/failure/with_successful_repo_creation/fails_to_add_the_user_to_the_repo_and_broadcasts.json
  spec/support/cassettes/AssignmentRepo_CreateGitHubRepositoryJob/failure/with_successful_repo_creation/fails_to_add_the_user_to_the_repo_and_logs.json
  spec/support/cassettes/AssignmentRepo_CreateGitHubRepositoryJob/failure/with_successful_repo_creation/fails_to_add_the_user_to_the_repo_and_reports.json
  spec/support/cassettes/AssignmentRepo_CreateGitHubRepositoryJob/failure/with_successful_repo_creation/fails_to_add_the_user_to_the_repo_and_retries.json
  spec/support/cassettes/AssignmentRepo_CreateGitHubRepositoryJob/failure/with_successful_repo_creation/fails_to_import_starter_code_and_broadcasts.json
  spec/support/cassettes/AssignmentRepo_CreateGitHubRepositoryJob/failure/with_successful_repo_creation/fails_to_import_starter_code_and_logs.json
  spec/support/cassettes/AssignmentRepo_CreateGitHubRepositoryJob/failure/with_successful_repo_creation/fails_to_import_starter_code_and_reports.json
  spec/support/cassettes/AssignmentRepo_CreateGitHubRepositoryJob/failure/with_successful_repo_creation/fails_to_import_starter_code_and_retries.json
  spec/support/cassettes/AssignmentRepo_CreateGitHubRepositoryJob/failure/with_successful_repo_creation/fails_to_save_the_AssignmentRepo_and_broadcasts.json
  spec/support/cassettes/AssignmentRepo_CreateGitHubRepositoryJob/failure/with_successful_repo_creation/fails_to_save_the_AssignmentRepo_and_logs.json
  spec/support/cassettes/AssignmentRepo_CreateGitHubRepositoryJob/failure/with_successful_repo_creation/fails_to_save_the_AssignmentRepo_and_reports.json
  spec/support/cassettes/AssignmentRepo_CreateGitHubRepositoryJob/failure/with_successful_repo_creation/fails_to_save_the_AssignmentRepo_and_retries.json
  spec/support/cassettes/AssignmentRepo_CreateGitHubRepositoryJob/successful_creation/broadcasts_status_on_channel.json
  spec/support/cassettes/AssignmentRepo_CreateGitHubRepositoryJob/successful_creation/creates_an_AssignmentRepo_as_a_member/has_the_same_user.json
  spec/support/cassettes/AssignmentRepo_CreateGitHubRepositoryJob/successful_creation/creates_an_AssignmentRepo_as_a_member/is_not_nil.json
  spec/support/cassettes/AssignmentRepo_CreateGitHubRepositoryJob/successful_creation/creates_an_AssignmentRepo_as_a_member/is_the_same_assignment.json
  spec/support/cassettes/AssignmentRepo_CreateGitHubRepositoryJob/successful_creation/creates_an_AssignmentRepo_as_an_outside_collaborator/has_the_same_user.json
  spec/support/cassettes/AssignmentRepo_CreateGitHubRepositoryJob/successful_creation/creates_an_AssignmentRepo_as_an_outside_collaborator/is_not_nil.json
  spec/support/cassettes/AssignmentRepo_CreateGitHubRepositoryJob/successful_creation/creates_an_AssignmentRepo_as_an_outside_collaborator/is_the_same_assignment.json
  spec/support/cassettes/AssignmentRepo_CreateGitHubRepositoryJob/successful_creation/kicks_off_a_cascading_porter_status_job.json
  spec/support/cassettes/AssignmentRepo_CreateGitHubRepositoryJob/successful_creation/tracks_create_fail_stat.json
  spec/support/cassettes/AssignmentRepo_CreateGitHubRepositoryJob/successful_creation/tracks_how_long_it_too_to_be_created.json
  spec/support/cassettes/AssignmentRepo_CreateGitHubRepositoryJob/successful_creation/tracks_the_how_long_it_too_to_be_created.json
  spec/support/cassettes/AssignmentRepo_CreateGitHubRepositoryJob/successful_creation/uses_the_create_repository_queue.json
  spec/support/cassettes/AssignmentRepo_CreateGitHubRepositoryJob/successful_creation/with_repository_import_webhook_enabled/does_not_kick_off_a_cascading_porter_status_job.json
  spec/support/cassettes/RepositoryImportEventJob/with_created_assignment_repo/doesn_t_broadcast.json
  spec/support/cassettes/RepositoryImportEventJob/with_created_assignment_repo/doesn_t_change_the_invite_status.json
  spec/support/cassettes/RepositoryImportEventJob/with_created_assignment_repo/doesn_t_report_any_stats.json
  spec/support/cassettes/RepositoryImportEventJob/with_created_assignment_repo/with_repository_import_webhook_enabled/with_source_import_failure/broadcasts_failure.json
  spec/support/cassettes/RepositoryImportEventJob/with_created_assignment_repo/with_repository_import_webhook_enabled/with_source_import_failure/reports_failure_stat.json
  spec/support/cassettes/RepositoryImportEventJob/with_created_assignment_repo/with_repository_import_webhook_enabled/with_source_import_failure/sets_invite_status_to_errored_importing_starter_code.json
  spec/support/cassettes/RepositoryImportEventJob/with_created_assignment_repo/with_repository_import_webhook_enabled/with_source_import_success/broadcasts_completion.json
  spec/support/cassettes/RepositoryImportEventJob/with_created_assignment_repo/with_repository_import_webhook_enabled/with_source_import_success/reports_success_stat.json
  spec/support/cassettes/RepositoryImportEventJob/with_created_assignment_repo/with_repository_import_webhook_enabled/with_source_import_success/sets_invite_status_to_completed.json
Labels: :rocket: ready for review, :sparkles: enhancement, create/import repo flow

#1547 Show repo_url, on page reload (if one exists)
  app/assets/javascripts/setupv2.js
Labels: :rocket: ready for review, create/import repo flow

#1554 Nil check in organization_event_job.rb
  app/jobs/organization_event_job.rb
  spec/jobs/organization_event_job_spec.rb
Labels: bug :beetle:, fix :hammer_and_wrench:, ready for review :writing_hand:

#1553 Removes repo_url presentation in the setup screen
  app/assets/javascripts/setupv2.js
  app/controllers/assignment_invitations_controller.rb
  app/jobs/assignment_repo/create_github_repository_job.rb
  app/jobs/repository_import_event_job.rb
  spec/controllers/assignment_invitations_controller_spec.rb
  spec/jobs/assignment_repo/create_github_repository_job_spec.rb
  spec/jobs/repository_import_event_job_spec.rb
  spec/support/cassettes/AssignmentInvitationsController/GET_progress/with_import_resiliency_enabled/when_the_github_repository_already_exists/has_a_repo_url_field_present.json
Labels: ready for review :writing_hand:, repository setup :package:

#1559 Fix roster es query
  app/controllers/orgs/rosters_controller.rb
Labels: bug :beetle:, fix :hammer_and_wrench:

#1581 Switch from Bonsai to Elasticsearch
  app.json
  config/chewy.yml
Labels: dependencies

#1582 Bump chewy version to 5.0.0
  Gemfile
  Gemfile.lock
  vendor/cache/chewy-0.10.1.gem
  vendor/cache/chewy-5.0.0.gem
  vendor/cache/elasticsearch-5.0.4.gem
  vendor/cache/elasticsearch-6.1.0.gem
  vendor/cache/elasticsearch-api-5.0.4.gem
  vendor/cache/elasticsearch-api-6.1.0.gem
  vendor/cache/elasticsearch-dsl-0.1.5.gem
  vendor/cache/elasticsearch-dsl-0.1.6.gem
  vendor/cache/elasticsearch-transport-5.0.4.gem
  vendor/cache/elasticsearch-transport-6.1.0.gem
Labels: dependencies

#1571 Group assignment repo setup front end
  app/assets/javascripts/setup.js
  app/views/assignment_invitations/setup.html.erb
  app/views/group_assignment_invitations/setup.html.erb
Labels: ready for review :writing_hand:, repository setup :package:

#1583 Migrations for GraphQL work to begin
  db/migrate/20180918215254_global_relay_fields_for_assignments_orgs_and_users.rb
  db/schema.rb
Labels: GraphQL

#1573 Require chewy
  config/chewy.rb
  config/initializers/chewy.rb
  config/initializers/sidekiq.rb
  lib/sidekiq/chewy_middleware.rb
Labels: dependencies, ready for review :writing_hand:

#1587 Bump ES to 6.3.2
  docker-compose.yml
Labels: dependencies

#1572 Redirect Classroom Assistant Updater to Release Server
  Gemfile
  Gemfile.lock
  config/initializers/rack_rewrite.rb
  vendor/cache/rack-rewrite-1.5.1.gem
Labels: classroom assistant :desktop_computer:, ready for review :writing_hand:

#1595 Change bug link to be the new bug link
  app/views/shared/_header.html.erb
  app/views/shared/_invitation_header.html.erb
Labels: enhancement :sparkles:, ready for review :writing_hand:

#1596 Delete (old) ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE.md
Labels: enhancement :sparkles:, ready for review :writing_hand:

#1588 Fix ES Headaches
  app/chewy/assignment_index.rb
  app/chewy/assignment_invitation_index.rb
  app/chewy/assignment_repo_index.rb
  app/chewy/deadline_index.rb
  app/chewy/group_assignment_index.rb
  app/chewy/group_assignment_invitation_index.rb
  app/chewy/group_assignment_repo_index.rb
  app/chewy/group_index.rb
  app/chewy/grouping_index.rb
  app/chewy/organization_index.rb
  app/chewy/repo_access_index.rb
  app/chewy/stafftools_index.rb
  app/chewy/user_index.rb
  app/controllers/stafftools/resources_controller.rb
  app/jobs/application_job.rb
  app/jobs/last_active_job.rb
  app/models/assignment.rb
  app/models/assignment_invitation.rb
  app/models/assignment_repo.rb
  app/models/group.rb
  app/models/group_assignment.rb
  app/models/group_assignment_invitation.rb
  app/models/group_assignment_repo.rb
  app/models/grouping.rb
  app/models/organization.rb
  app/models/repo_access.rb
  app/models/user.rb
  db/migrate/20160611232013_set_user_last_active_at_value.rb
  lib/multi_index_search_request.rb
  spec/controllers/stafftools/resources_controller_spec.rb
  spec/support/cassettes/DestroyResourceJob/destroys_the_resource.json
  spec/support/cassettes/Stafftools_ResourcesController/GET_index/as_an_authorized_user/with_URL_parameters/has_a_MultiIndexSearchRequest_of_resources.json
  spec/support/cassettes/Stafftools_ResourcesController/GET_index/as_an_authorized_user/with_URL_parameters/has_a_StafftoolsIndex_Query_of_resources.json
  spec/support/cassettes/Stafftools_ResourcesController/GET_search/as_an_authorized_user/with_URL_parameters/has_a_MultiIndexSearchRequest_of_resources.json
  spec/support/cassettes/Stafftools_ResourcesController/GET_search/as_an_authorized_user/with_URL_parameters/has_a_StafftoolsIndex_Query_of_resources.json
Labels: dependencies, fix :hammer_and_wrench:, ready for review :writing_hand:

#1480 Classroom Home Page and Classroom Desktop Landing Page
  app/assets/images/classroom-assistant-downloading.png
  app/assets/images/classroom-logo.png
  app/assets/images/schools/Brown University.png
  app/assets/images/schools/University of Canterbury.png
  app/assets/images/schools/University of San Francisco.png
  app/assets/images/schools/e3 Civic High School.png
  app/assets/images/wordmark@2x.png
  app/assets/javascripts/os.js
  app/assets/javascripts/pages.js
  app/assets/stylesheets/components/buttons.scss
  app/assets/stylesheets/components/desktop.scss
  app/assets/stylesheets/layout.scss
  app/controllers/application_controller/feature_flags_dependency.rb
  app/controllers/pages_controller.rb
  app/helpers/i18n_helper.rb
  app/views/layouts/pagesv2.html.erb
  app/views/pages/_back_to_classroom_header.html.erb
  app/views/pages/_download_desktop_button.html.erb
  app/views/pages/_header.html.erb
  app/views/pages/_sign_in_section.html.erb
  app/views/pages/assistant.html.erb
  app/views/pages/home.html.erb
  app/views/pages/homev2.html.erb
  config/locales/views/pages/en.yml
  config/locales/views/shared/en.yml
  config/routes.rb
  db/schema.rb
Labels: classroom assistant :desktop_computer:, ready for review :writing_hand:

#1600 Allow yellow status
  config/application.rb
Labels: dependencies, ready for review :writing_hand:

#1606 Removed Deadline index and type
  app/chewy/deadline_index.rb
  app/controllers/stafftools/resources_controller.rb
Labels: dependencies, ready for review :writing_hand:

#1599 Use `stale` instead of `wontfix`
  .github/stale.yml
Labels: enhancement :sparkles:

#1594 Add Group Assignment Repo handler to `repository_import` event job
  app/jobs/repository_import_event_job.rb
  spec/jobs/repository_import_event_job_spec.rb
  spec/support/cassettes/RepositoryImportEventJob/with_created_group_assignment_repo/doesn_t_broadcast.json
  spec/support/cassettes/RepositoryImportEventJob/with_created_group_assignment_repo/doesn_t_change_the_invite_status.json
  spec/support/cassettes/RepositoryImportEventJob/with_created_group_assignment_repo/doesn_t_report_any_stats.json
  spec/support/cassettes/RepositoryImportEventJob/with_created_group_assignment_repo/with_group_import_resiliency_enabled/with_source_import_failure/broadcasts_failure.json
  spec/support/cassettes/RepositoryImportEventJob/with_created_group_assignment_repo/with_group_import_resiliency_enabled/with_source_import_failure/reports_failure_stat.json
  spec/support/cassettes/RepositoryImportEventJob/with_created_group_assignment_repo/with_group_import_resiliency_enabled/with_source_import_failure/sets_invite_status_to_errored_importing_starter_code.json
  spec/support/cassettes/RepositoryImportEventJob/with_created_group_assignment_repo/with_group_import_resiliency_enabled/with_source_import_success/broadcasts_completion.json
  spec/support/cassettes/RepositoryImportEventJob/with_created_group_assignment_repo/with_group_import_resiliency_enabled/with_source_import_success/reports_success_stat.json
  spec/support/cassettes/RepositoryImportEventJob/with_created_group_assignment_repo/with_group_import_resiliency_enabled/with_source_import_success/sets_invite_status_to_completed.json
Labels: ready for review :writing_hand:, repository setup :package:

#1601 Turn off autocomplete in stafftools
  app/views/stafftools/resources/index.html.erb
Labels: enhancement :sparkles:, ready for review :writing_hand:

#1567 Added 'cancelled' status handling to repository_import_event_job.rb
  app/jobs/repository_import_event_job.rb
  spec/fixtures/files/webhook_events/repository_import_cancelled.json
  spec/jobs/repository_import_event_job_spec.rb
  spec/support/cassettes/RepositoryImportEventJob/with_created_assignment_repo/with_repository_import_webhook_enabled/with_source_import_cancelled/broadcasts_cancelled.json
  spec/support/cassettes/RepositoryImportEventJob/with_created_assignment_repo/with_repository_import_webhook_enabled/with_source_import_cancelled/reports_cancelled_stat.json
  spec/support/cassettes/RepositoryImportEventJob/with_created_assignment_repo/with_repository_import_webhook_enabled/with_source_import_cancelled/sets_invite_status_to_errored_importing_starter_code.json
  spec/support/cassettes/RepositoryImportEventJob/with_created_group_assignment_repo/with_group_import_resiliency_enabled/with_source_import_cancelled/broadcasts_cancelled.json
  spec/support/cassettes/RepositoryImportEventJob/with_created_group_assignment_repo/with_group_import_resiliency_enabled/with_source_import_cancelled/reports_cancelled_stat.json
  spec/support/cassettes/RepositoryImportEventJob/with_created_group_assignment_repo/with_group_import_resiliency_enabled/with_source_import_cancelled/sets_invite_status_to_errored_importing_starter_code.json
Labels: repository setup :package:

#1610 Report handled octokit errors to datadog
  lib/github/errors.rb
  spec/jobs/assignment_repo/create_github_repository_job_spec.rb
  spec/jobs/group_assignment_repo/create_github_repository_job_spec.rb
  spec/lib/github/errors_spec.rb
  spec/models/assignment_repo/creator_spec.rb
Labels: enhancement :sparkles:, ready for review :writing_hand:

#1598 Move flipper from user to group_assignment
  app/controllers/application_controller/feature_flags_dependency.rb
  app/controllers/group_assignment_invitations_controller.rb
  app/jobs/repository_import_event_job.rb
  app/models/group_assignment_invitation.rb
  spec/models/group_assignment_invitation_spec.rb
Labels: ready for review :writing_hand:, repository setup :package:

#1612 Remove TODOs
  app/jobs/group_assignment_repo/create_github_repository_job.rb
  spec/jobs/group_assignment_repo/create_github_repository_job_spec.rb
Labels: No Op, ready for review :writing_hand:, repository setup :package:
