Repository education/classroom, pull requests merged in 2019-05, with the labels that each got.

#1817 Drop Ticker Stat Schema
  db/schema.rb
Labels: bug :beetle:

#1822 Upgrade Jquery
  package.json
  yarn.lock
Labels: dependencies

#1820 Fix Assignment Sorting on Dashboard
  app/views/organizations/_organization_card_layout.html.erb
Labels: bug :beetle:

#1831 Fix header styling on assignment invitations
  app/views/shared/_invitation_header.html.erb
Labels: fix :hammer_and_wrench:

#1836 Show Repo URL when created (while still importing)
  app/assets/javascripts/setup.js
  app/controllers/assignment_invitations_controller.rb
  app/jobs/assignment_repo/create_github_repository_job.rb
  spec/controllers/assignment_invitations_controller_spec.rb
  spec/jobs/assignment_repo/create_github_repository_job_spec.rb
  spec/support/cassettes/AssignmentInvitationsController/POST_create_repo/with_import_resiliency_enabled/when_a_repo_exists/has_a_repo_url.json
  spec/support/cassettes/AssignmentRepo_CreateGitHubRepositoryJob/successful_creation/creates_an_AssignmentRepo_as_a_member/has_a_github_global_relay_id.json
  spec/support/cassettes/AssignmentRepo_CreateGitHubRepositoryJob/successful_creation/creates_an_AssignmentRepo_as_an_outside_collaborator/has_a_github_global_relay_id.json
  spec/support/cassettes/AssignmentRepo_CreateGitHubRepositoryJob/successful_creation/tracks_create_success_stat.json
Labels: enhancement :sparkles:, repository setup :package:

#1665 Disable the "Download Repositories" button
  app/views/assignments/show.html.erb
  app/views/group_assignments/show.html.erb
  app/views/shared/_open_on_assistant_modal.html.erb
Labels: enhancement :sparkles:, fix :hammer_and_wrench:

#1843 Link to issues page
  app/views/shared/_header.html.erb
  app/views/shared/_invitation_header.html.erb
Labels: enhancement :sparkles:
