Repository education/classroom, pull requests merged in 2019-08, with the labels that each got.

#2142 Move before actions to Google Configurations
  app/controllers/orgs/google_classroom_configurations_controller.rb
  app/controllers/orgs/rosters_controller/google_classroom_dependency.rb
  spec/controllers/orgs/google_classroom_configurations_controller_spec.rb
  spec/controllers/orgs/rosters_controller_spec.rb
  spec/support/cassettes/Orgs_GoogleClassroomConfigurationsController/_create/with_flipper_on/when_the_user_is_authorized/there_is_a_LTI_configuration/flashes_error_message.json
  spec/support/cassettes/Orgs_GoogleClassroomConfigurationsController/_create/with_flipper_on/when_the_user_is_authorized/there_is_a_LTI_configuration/redirects_to_settings_page.json
  spec/support/cassettes/Orgs_GoogleClassroomConfigurationsController/_create/with_flipper_on/when_the_user_is_authorized/there_is_a_roster/flashes_error_message.json
  spec/support/cassettes/Orgs_GoogleClassroomConfigurationsController/_create/with_flipper_on/when_the_user_is_authorized/there_is_a_roster/redirects_to_settings_page.json
  spec/support/cassettes/Orgs_GoogleClassroomConfigurationsController/_index/with_flipper_on/when_the_user_is_authorized/there_is_a_LTI_configuration/flashes_error_message.json
  spec/support/cassettes/Orgs_GoogleClassroomConfigurationsController/_index/with_flipper_on/when_the_user_is_authorized/there_is_a_LTI_configuration/redirects_to_settings_page.json
  spec/support/cassettes/Orgs_GoogleClassroomConfigurationsController/_index/with_flipper_on/when_the_user_is_authorized/there_is_a_roster/flashes_error_message.json
  spec/support/cassettes/Orgs_GoogleClassroomConfigurationsController/_index/with_flipper_on/when_the_user_is_authorized/there_is_a_roster/redirects_to_settings_page.json
Labels: Google Classroom

#2132 LMS Support Docs
  app/controllers/pages_controller.rb
  docs/connect-to-lms.md
  docs/generate-lms-credentials.md
  docs/help.md
  docs/setup-canvas.md
  docs/setup-generic-lms.md
  docs/setup-moodle.md
  public/images/help/lms/canvas/prerequisites.png
  public/images/help/lms/canvas/step-4.png
  public/images/help/lms/canvas/step-6.png
  public/images/help/lms/canvas/step-7.png
  public/images/help/lms/canvas/step-9.png
  public/images/help/lms/canvas/success.png
  public/images/help/lms/canvas/troubleshooting-1.png
  public/images/help/lms/generic/prerequisites.png
  public/images/help/lms/generic/success.png
  public/images/help/lms/github-classroom-credentials.png
  public/images/help/lms/moodle/prerequisites.png
  public/images/help/lms/moodle/step-10.png
  public/images/help/lms/moodle/step-11.png
  public/images/help/lms/moodle/step-13.png
  public/images/help/lms/moodle/step-15.png
  public/images/help/lms/moodle/step-17.png
  public/images/help/lms/moodle/step-19.png
  public/images/help/lms/moodle/step-3.png
  public/images/help/lms/moodle/step-4.png
  public/images/help/lms/moodle/step-5.png
  public/images/help/lms/moodle/step-6.png
  public/images/help/lms/moodle/step-8.png
  public/images/help/lms/moodle/success.png
Labels: LMS Integration :school:

#2148 LMS Configuration UI Touchups
  app/views/organizations/edit.html.erb
  app/views/organizations/link_lms.html.erb
  app/views/orgs/lti_configurations/show.html.erb
Labels: ui :art:

#2126 Remove archived classes from list of google classrooms
  app/controllers/orgs/google_classroom_configurations_controller.rb
Labels: Google Classroom

#2149 Update UI on Select Google Classroom Page
  app/controllers/orgs/google_classroom_configurations_controller.rb
  app/views/orgs/google_classroom_configurations/_google_classroom_collection.html.erb
  app/views/orgs/google_classroom_configurations/index.html.erb
Labels: Google Classroom, ui :art:

#2151 Update Link LMS to match new style
  app/models/lti_configuration.rb
  app/views/organizations/link_lms.html.erb
Labels: Google Classroom, LMS Integration :school:, ui :art:

#2153 Run API-calling validators only when related attribute is changed
  app/models/assignment.rb
  app/models/concerns/starter_code_importable.rb
  app/models/group_assignment.rb
  spec/models/assignment_spec.rb
  spec/models/group_assignment_spec.rb
  spec/support/cassettes/GroupAssignment/_starter_code_repository_not_empty/updating_or_creating_assignment/does_not_run_validation_method_if_starter_code_repo_id_is_unchanged.json
  spec/support/cassettes/GroupAssignment/_starter_code_repository_not_empty/updating_or_creating_assignment/runs_validation_method_if_starter_code_repo_id_is_changed.json
Labels: Tech Debt 🧱

#2156 Update invite admins page
  app/views/organizations/_invite_users.html.erb
  app/views/organizations/_organization_user.html.erb
  app/views/organizations/_organization_users.html.erb
  app/views/organizations/invitation.html.erb
  app/views/organizations/invite.html.erb
Labels: ui :art:

#2155 Add confirmation modal for archiving classrooms
  app/views/organizations/_archive_modal.html.erb
  app/views/organizations/edit.html.erb
  config/locales/views/organizations/en.yml
Labels: after-life ⚰️

#2133 Fix bug when there is an error on classroom settings
  app/controllers/organizations_controller.rb
  spec/controllers/organizations_controller_spec.rb
  spec/support/cassettes/OrganizationsController/PATCH_update/correctly_updates_the_organization.json
  spec/support/cassettes/OrganizationsController/PATCH_update/when_fail/not_change_current_organization_title.json
  spec/support/cassettes/OrganizationsController/PATCH_update/when_success/correctly_updates_the_organization.json
Labels: bug :beetle:

#2159 Add classroom name to delete modal
  app/views/organizations/_reset_and_remove_organization_modal.html.erb
  config/locales/views/organizations/en.yml
Labels: enhancement :sparkles:

#2160 Disable assignment invitations when classroom is archived
  app/models/assignment_invitation.rb
  app/models/curl -H "Content-Type: application:json" -d '{"pri
  app/models/group_assignment_invitation.rb
  app/models/organization.rb
  spec/models/assignment_invitation_spec.rb
  spec/models/group_assignment_invitation_spec.rb
  spec/support/cassettes/GroupAssignmentInvitation/_redeem_for/classroom_is_archived/fails_with_proper_error_message.json
Labels: after-life ⚰️

#2167 Add LMS user id field on Roster Entries table
  db/migrate/20190805155741_rename_field_google_lms.rb
  db/schema.rb
Labels: Google Classroom, LMS Integration :school:

#2180 Create backfill for "lms_user_id"
  lib/tasks/backfill_lms_user_ids.rake
Labels: Google Classroom, student roster :man_student: :woman_student:

#2170 Add cached_launch_message_nonce to LtiConfiguration
  db/migrate/20190805192704_add_cached_launch_message_nonce_to_lti_configuration.rb
  db/schema.rb
Labels: maintenance 🛠

#2140 Course dashboard sorting
  app/assets/javascripts/repo-search-and-sort.js
  app/assets/javascripts/search-and-sort.js
  app/assets/javascripts/select_menu.js
  app/controllers/assignments_controller.rb
  app/controllers/group_assignments_controller.rb
  app/controllers/organizations_controller.rb
  app/models/organization.rb
  app/views/assignments/_filterable_assignment_roster_list.html.erb
  app/views/assignments/filter_repos.js.erb
  app/views/group_assignments/_filterable_group_assignment_repo_list.html.erb
  app/views/group_assignments/filter_repos.js.erb
  app/views/organizations/index.html.erb
  app/views/organizations/search.js.erb
  app/views/shared/_search_and_sort.html.erb
  spec/controllers/organizations_controller_spec.rb
  spec/support/cassettes/OrganizationsController/sort_organizations/sorts_organizations_by_name.json
  spec/support/cassettes/OrganizationsController/sort_organizations/sorts_organizations_by_newest_first.json
  spec/support/cassettes/OrganizationsController/sort_organizations/sorts_organizations_by_oldest_first.json
Labels: enhancement :sparkles:, ui :art:

#2168 Don't show "Import by" option to user if that attribute type is all nil
  app/controllers/orgs/rosters_controller/lti_dependency.rb
  app/views/orgs/rosters/_select_identifier_modal.html.erb
  app/views/orgs/rosters/import_from_lms.html.erb
  app/views/orgs/rosters/import_from_lms.js.erb
  app/views/orgs/rosters/show.html.erb
  spec/controllers/orgs/rosters_controller_spec.rb
  spec/support/cassettes/Orgs_RostersController/GET_import_lms_roster/with_lti_launch_enabled/with_existing_LMS/with_context_membership_url/fetching_roster_succeeds/all_attributes_present/format_html_succeeds.json
  spec/support/cassettes/Orgs_RostersController/GET_import_lms_roster/with_lti_launch_enabled/with_existing_LMS/with_context_membership_url/fetching_roster_succeeds/all_attributes_present/format_js_succeeds.json
  spec/support/cassettes/Orgs_RostersController/GET_import_lms_roster/with_lti_launch_enabled/with_existing_LMS/with_context_membership_url/fetching_roster_succeeds/all_attributes_present/sends_statsd.json
  spec/support/cassettes/Orgs_RostersController/GET_import_lms_roster/with_lti_launch_enabled/with_existing_LMS/with_context_membership_url/fetching_roster_succeeds/successful_fetch_but_missing_all_attributes/sets_flash_if_all_options_are_nil_lists.json
  spec/support/cassettes/Orgs_RostersController/GET_import_lms_roster/with_lti_launch_enabled/with_existing_LMS/with_context_membership_url/fetching_roster_succeeds/successful_fetch_but_missing_some_attributes/hides_options_when_they_re_nil_lists.json
Labels: LMS Integration :school:, fix :hammer_and_wrench:, ui :art:

#2176 Support LTI 1.0 responses
  app/controllers/orgs/rosters_controller/lti_dependency.rb
  lib/github_classroom/lti/membership_service.rb
  lib/github_classroom/lti/mixins/request_signing.rb
  lib/github_classroom/lti/models/course_member.rb
  lib/github_classroom/lti/models/membership_extension/member.rb
  lib/github_classroom/lti/models/membership_extension/membership.rb
  lib/github_classroom/lti/models/membership_extension/message_response.rb
  lib/github_classroom/lti/models/membership_extension/status_info.rb
  lib/github_classroom/lti/models/membership_service/member.rb
  lib/github_classroom/lti/models/membership_service/membership.rb
  lib/github_classroom/lti/models/membership_service/membership_subject.rb
  spec/controllers/orgs/rosters_controller_spec.rb
  spec/lib/github_classroom/lti/membership_service_spec.rb
  spec/lib/github_classroom/lti/mixins/request_siging_spec.rb
  spec/support/cassettes/GitHubClassroom_LTI_MembershipService/membership/invalid_authentication/cannot_get_members.json
  spec/support/cassettes/GitHubClassroom_LTI_MembershipService/membership/valid_authentication/gets_all_membership.json
  spec/support/cassettes/GitHubClassroom_LTI_MembershipService/membership/valid_authentication/gets_only_instructors.json
  spec/support/cassettes/GitHubClassroom_LTI_MembershipService/membership/valid_authentication/gets_only_students.json
  spec/support/cassettes/GitHubClassroom_LTI_MembershipService/membership_extension_LTI_1_0_/valid_authentication/gets_membership.json
  spec/support/cassettes/GitHubClassroom_LTI_MembershipService/membership_service_LTI_1_1_/invalid_authentication/cannot_get_members.json
  spec/support/cassettes/GitHubClassroom_LTI_MembershipService/membership_service_LTI_1_1_/valid_authentication/gets_all_membership.json
  spec/support/cassettes/GitHubClassroom_LTI_MembershipService/membership_service_LTI_1_1_/valid_authentication/gets_only_instructors.json
  spec/support/cassettes/GitHubClassroom_LTI_MembershipService/membership_service_LTI_1_1_/valid_authentication/gets_only_students.json
Labels: LMS Integration :school:

#2174 Show LMS Capabilities based on most recent information
  app/controllers/orgs/rosters_controller/lti_dependency.rb
  app/controllers/sessions_controller.rb
  app/models/lti_configuration.rb
  app/models/lti_configuration/blackboard_settings.rb
  app/models/lti_configuration/canvas_settings.rb
  app/models/lti_configuration/generic_settings.rb
  app/models/lti_configuration/membership/settings.rb
  app/models/lti_configuration/moodle_settings.rb
  app/views/orgs/lti_configurations/complete.html.erb
  lib/github_classroom/lti/message_store.rb
  spec/factories.rb
  spec/integration/lti_launch_spec.rb
  spec/lib/github_classroom/lti/lti_message_store_spec.rb
  spec/models/lti_configuration/blackboard_settings_spec.rb
  spec/models/lti_configuration/brightspace_settings_spec.rb
  spec/models/lti_configuration/canvas_settings_spec.rb
  spec/models/lti_configuration/generic_settings_spec.rb
  spec/models/lti_configuration/moodle_settings_spec.rb
  spec/models/lti_configuration_spec.rb
Labels: LMS Integration :school:

#2189 Front-end changes to archived classrooms
  app/controllers/organizations_controller.rb
  app/models/organization.rb
  app/views/organizations/_organization_banner.html.erb
Labels: after-life ⚰️

#2177 Allow duplicate roster entries
  app/controllers/orgs/rosters_controller.rb
  app/models/concerns/duplicate_roster_entries.rb
  app/models/roster.rb
  app/models/roster/creator.rb
  app/models/roster_entry.rb
  spec/controllers/orgs/rosters_controller_spec.rb
  spec/models/roster_entry_spec.rb
  spec/support/cassettes/Orgs_RostersController/PATCH_add_students/when_there_are_duplicate_identifiers/creates_roster_entries.json
  spec/support/cassettes/Orgs_RostersController/PATCH_add_students/when_there_are_duplicate_identifiers/finds_identifiers_with_suffix.json
  spec/support/cassettes/Orgs_RostersController/PATCH_add_students/when_there_are_duplicate_identifiers/redirects_to_rosters_page.json
  spec/support/cassettes/Orgs_RostersController/PATCH_add_students/when_there_are_duplicate_identifiers/sets_flash_message.json
  spec/support/cassettes/Orgs_RostersController/PATCH_sync_google_classroom/with_student_identifier_flipper_enabled/with_google_classroom_flipper_enabled/when_user_is_authorized_with_google/classroom_has_a_linked_google_course/appends_suffix_with_duplicate_students_that_were_already_added_to_roster.json
Labels: Google Classroom, LMS Integration :school:, student roster :man_student: :woman_student:

#2178 Allow editing of roster entries
  app/controllers/orgs/rosters_controller.rb
  app/views/orgs/rosters/_edit_roster_entry_modal.html.erb
  app/views/orgs/rosters/_roster_entry.html.erb
  app/views/orgs/rosters/show.html.erb
  config/routes.rb
  spec/controllers/orgs/rosters_controller_spec.rb
  spec/support/cassettes/Orgs_RostersController/PATCH_edit_entry/when_renaming_to_an_identifier_that_does_not_exist/displays_success_message.json
  spec/support/cassettes/Orgs_RostersController/PATCH_edit_entry/when_renaming_to_an_identifier_that_does_not_exist/redirects_to_roster_page.json
  spec/support/cassettes/Orgs_RostersController/PATCH_edit_entry/when_renaming_to_an_identifier_that_does_not_exist/updates_roster_entry.json
  spec/support/cassettes/Orgs_RostersController/PATCH_edit_entry/when_renaming_to_an_identifier_that_exists/displays_success_message.json
  spec/support/cassettes/Orgs_RostersController/PATCH_edit_entry/when_renaming_to_an_identifier_that_exists/does_not_update_roster_entry.json
  spec/support/cassettes/Orgs_RostersController/PATCH_edit_entry/when_renaming_to_an_identifier_that_exists/redirects_to_roster_page.json
Labels: student roster :man_student: :woman_student:

#2181 Start using "lms_user_id"
  app/controllers/orgs/rosters_controller.rb
  app/controllers/orgs/rosters_controller/google_classroom_dependency.rb
  app/controllers/orgs/rosters_controller/lti_dependency.rb
  app/models/roster/creator.rb
  app/models/roster_entry.rb
  app/views/orgs/rosters/import_from_lms.html.erb
  spec/controllers/orgs/rosters_controller_spec.rb
  spec/support/cassettes/Orgs_RostersController/PATCH_sync_google_classroom/with_student_identifier_flipper_enabled/with_google_classroom_flipper_enabled/when_user_is_authorized_with_google/classroom_has_a_linked_google_course/does_not_add_duplicate_students_that_were_already_added_to_roster.json
Labels: Google Classroom, LMS Integration :school:

#2203 Add sakai support
  app/controllers/orgs/rosters_controller/lti_dependency.rb
  app/models/lti_configuration.rb
  app/models/lti_configuration/sakai_settings.rb
Labels: LMS Integration :school:

#2193 Add message indicating empty unlinked user list
  app/views/orgs/rosters/_link_to_github_account_modal.html.erb
Labels: enhancement :sparkles:

#2171 Revise LMS docs
  docs/connect-to-lms.md
  docs/generate-lms-credentials.md
  docs/setup-canvas.md
  docs/setup-generic-lms.md
  docs/setup-moodle.md
Labels: LMS Integration :school:

#2205 Google Classroom / LTI better error messages
  app/controllers/orgs/google_classroom_configurations_controller.rb
  app/controllers/orgs/lti_configurations_controller.rb
  app/controllers/orgs/rosters_controller/lti_dependency.rb
  app/controllers/sessions_controller.rb
  app/controllers/sessions_controller/lti_dependency.rb
  app/models/lti_configuration.rb
  app/views/orgs/rosters/_select_identifier_modal.html.erb
  app/views/orgs/rosters/import_from_lms.js.erb
  app/views/sessions/lti_launch.html.erb
  config/routes.rb
  lib/github_classroom/lti/message_store.rb
  lib/omniauth/strategies/lti.rb
  spec/controllers/orgs/google_classroom_configurations_controller_spec.rb
  spec/controllers/orgs/lti_configurations_controller_spec.rb
  spec/controllers/orgs/rosters_controller_spec.rb
  spec/controllers/sessions_controller_spec.rb
  spec/integration/lti_launch_spec.rb
  spec/lib/github_classroom/lti/message_store_spec.rb
  spec/support/cassettes/SessionsController/sessions_lti_launch/authenticated_request/post_launch_url_is_set_to_LtiConfigurations_complete.json
  spec/support/omniauth.rb
Labels: Google Classroom, LMS Integration :school:, ui :art:

#2163 Enable all of the features in development
  lib/tasks/enable_features.rake
Labels: fix :hammer_and_wrench:

#2164 Allow for docker to be installed outside of homebrew
  Brewfile
Labels: fix :hammer_and_wrench:

#2165 Add an entry for classroom.github.localhost to nginx
  config/dev/nginx.conf.erb
Labels: fix :hammer_and_wrench:

#2209 Tie up LTI loose ends
  app/controllers/sessions_controller/lti_dependency.rb
  app/views/orgs/rosters/_select_identifier_modal.html.erb
Labels: fix :hammer_and_wrench:

#2218 Cange lti_launch to :post
  config/routes.rb
  spec/integration/lti_launch_spec.rb
Labels: Security

#2217 Change "Learning Management System" to "learning management system"
  app/controllers/orgs/google_classroom_configurations_controller.rb
  app/controllers/orgs/lti_configurations_controller.rb
  app/controllers/orgs/rosters_controller/lti_dependency.rb
  app/controllers/sessions_controller/lti_dependency.rb
  app/helpers/lti_configuration_helper.rb
  app/models/lti_configuration.rb
  app/views/organizations/edit.html.erb
  app/views/organizations/link_lms.html.erb
  app/views/orgs/lti_configurations/_form.html.erb
  app/views/orgs/lti_configurations/complete.html.erb
  app/views/orgs/lti_configurations/info.html.erb
  app/views/orgs/lti_configurations/new.html.erb
  app/views/orgs/lti_configurations/show.html.erb
  app/views/orgs/rosters/_new_student_modal.html.erb
  app/views/orgs/rosters/_select_identifier_modal.html.erb
  app/views/orgs/rosters/import_from_lms.html.erb
  app/views/orgs/rosters/import_from_lms.js.erb
  app/views/orgs/rosters/new.html.erb
  app/views/orgs/rosters/show.html.erb
  app/views/sessions/lti_launch.html.erb
  docs/generate-lms-credentials.md
  docs/setup-generic-lms.md
  spec/controllers/orgs/google_classroom_configurations_controller_spec.rb
  spec/controllers/orgs/lti_configurations_controller_spec.rb
  spec/models/lti_configuration_spec.rb
Labels: ui :art:

#2220 Rename Assignment::RepositoryVisibilityJob to a single class
  app/jobs/assignment/repository_visibility_job.rb
  app/jobs/assignment_repository_visibility_job.rb
  app/models/assignment/editor.rb
  spec/controllers/assignments_controller_spec.rb
  spec/controllers/group_assignments_controller_spec.rb
  spec/jobs/repository_visibility_job_spec.rb
  spec/models/assignment/editor_spec.rb
Labels: fix :hammer_and_wrench:

#2201 Add Roster Import from LMS support guide
  app/controllers/pages_controller.rb
  docs/connect-to-lms.md
  docs/help.md
  docs/import-roster-from-lms.md
  docs/setup-canvas.md
  docs/setup-generic-lms.md
  docs/setup-moodle.md
  public/images/help/lms/roster-import/import-roster.gif
  public/images/help/lms/roster-import/sync-roster.gif
Labels: LMS Integration :school:

#2235 [Hotfix!] Avoid creating duplicate roster entries after creation
  app/controllers/orgs/rosters_controller.rb
  app/views/orgs/rosters/_select_identifier_modal.html.erb
  spec/controllers/orgs/rosters_controller_spec.rb
  spec/factories.rb
  spec/support/cassettes/Orgs_RostersController/GET_import_lms_roster/with_lti_launch_enabled/with_existing_LMS/with_context_membership_url/fetching_roster_succeeds/all_attributes_present/no_new_students/creates_no_duplicate_entries.json
Labels: bug :beetle:, fix :hammer_and_wrench:

#2232 Validate Grouping while validating GroupAssignment
  app/models/group_assignment.rb
  app/view_models/form_view.rb
  app/views/group_assignments/_group_assignment_form_options.html.erb
  spec/models/group_assignment_spec.rb
  spec/view_models/form_view_spec.rb
Labels: fix :hammer_and_wrench:

#2231 Add 406 Error Handling for Requests for Non-Specified Formats
  app/controllers/application_controller.rb
  public/406.html
  spec/controllers/application_controller_spec.rb
  spec/support/cassettes/ApplicationController/error_handling/returns_406_and_notifies_statsd_for_unknown_format.json
  spec/support/cassettes/ApplicationController/error_handling/returns_406_and_notifies_statsd_when_a_template_cannot_be_found.json
Labels: deploy:queued

#2211 Add dependent destroy to roster entries
  app/models/roster.rb
  spec/models/roster_spec.rb
Labels: student roster :man_student: :woman_student:

#2157 Updating assignments with the new UI
  app/assets/stylesheets/layout.scss
  app/views/assignments/_assignment.html.erb
  app/views/group_assignments/_group_assignment.html.erb
  app/views/organizations/show.html.erb
  app/views/shared/invitations/_clipboard_form.html.erb
  config/locales/views/organizations/en.yml
Labels: ui :art:

#2245 Clean up error dialog box removal
  app/assets/javascripts/assignment_form.js
  app/views/assignments/_assignment_form_options.html.erb
Labels: deploy:queued

#2252 Center support doc images on safari
  docs/generate-lms-credentials.md
  docs/import-roster-from-lms.md
  docs/probot-settings.md
  docs/setup-canvas.md
  docs/setup-generic-lms.md
  docs/setup-moodle.md
  docs/upgrade-your-organization.md
Labels: fix :hammer_and_wrench:

#2223 Assignment invitation URL improvements
  app/assets/javascripts/assignments.js
  app/assets/stylesheets/layout.scss
  app/controllers/assignments_controller.rb
  app/controllers/group_assignments_controller.rb
  app/views/assignments/toggle_invitations.js.erb
  app/views/group_assignments/toggle_invitations.js.erb
  app/views/shared/_invitation.html.erb
  app/views/shared/invitations/_desktop.html.erb
  app/views/shared/invitations/_mobile.html.erb
  config/locales/views/shared/en.yml
  config/routes.rb
  spec/controllers/assignments_controller_spec.rb
  spec/controllers/group_assignments_controller_spec.rb
  spec/support/cassettes/AssignmentsController/POST_toggle_invitations/updates_the_Assignment_s_invitations_enabled_column.json
  spec/support/cassettes/GroupAssignmentsController/POST_toggle_invitations/updates_the_Assignment_s_invitations_enabled_column.json
Labels: enhancement :sparkles:

#2255 Move invitations URL and admin permissions form options to optional section
  app/views/assignments/_assignment_form_options.html.erb
  app/views/group_assignments/_group_assignment_form_options.html.erb
Labels: ui :art:

#2258 Make MOTD responsive
  app/views/shared/_message_of_the_day.html.erb
Labels: bug :beetle:, ui :art:

#2246 Handle paginated membership service responses
  lib/github_classroom/lti/membership_service.rb
  lib/github_classroom/lti/mixins/request_signing.rb
  spec/lib/github_classroom/lti/membership_service_spec.rb
  spec/support/cassettes/GitHubClassroom_LTI_MembershipService/membership_service_LTI_1_1_/valid_authentication/pagination/collects_all_pages_of_results_into_one_list.json
  spec/support/cassettes/GitHubClassroom_LTI_MembershipService/membership_service_LTI_1_1_/valid_authentication/pagination/gets_the_membership_for_each_page.json
Labels: LMS Integration :school:

#2266 Improve UX/UI for Roster List Shown when an Assignment is Accepted
  app/controllers/assignment_invitations_controller.rb
  app/views/shared/_shared_join_roster.html.erb
Labels: deploy:queued

#2272 Mention file size limit for templates in docs
  docs/using-template-repos-for-assignments.md
Labels: deploy:queued

#2269 unrevert plan info in assignment form
  app/models/concerns/github_plan.rb
  app/models/organization.rb
  app/services/create_github_repo_service.rb
  app/view_models/form_view.rb
  app/views/assignments/_assignment_form_options.html.erb
  app/views/group_assignments/_group_assignment_form_options.html.erb
  spec/services/create_github_repo_service_spec.rb
Labels: deploy:queued

#2244 Fix auth failure redirect
  app/controllers/sessions_controller/lti_dependency.rb
  config/initializers/omniauth.rb
  lib/omniauth/authorization_failure_endpoint.rb
  lib/omniauth/strategies/lti.rb
  spec/controllers/sessions_controller_spec.rb
  spec/integration/lti_launch_spec.rb
  spec/support/cassettes/LTI_launch/sessions_lti_launch/valid_launch/authenticated_request/post_launch_url_is_set_to_LtiConfigurations_complete.json
Labels: LMS Integration :school:, bug :beetle:, fix :hammer_and_wrench:

#2280 Fixes setting private assignments to public
  app/views/assignments/_assignment_form_options.html.erb
  app/views/group_assignments/_group_assignment_form_options.html.erb
Labels: fix :hammer_and_wrench:

#2283 Run template repo validator when import method changed
  app/models/assignment.rb
  app/models/group_assignment.rb
  spec/models/assignment_spec.rb
  spec/models/group_assignment_spec.rb
  spec/support/cassettes/Assignment/validation_methods_that_call_API/_starter_code_repository_is_template/is_called_if_both_starter_code_repo_id_and_template_repos_enabled_are_changed.json
  spec/support/cassettes/Assignment/validation_methods_that_call_API/_starter_code_repository_is_template/is_called_if_starter_code_repo_id_is_changed.json
  spec/support/cassettes/GroupAssignment/validation_methods_that_call_API/_starter_code_repository_is_template/is_called_if_both_starter_code_repo_id_and_template_repos_enabled_are_changed.json
  spec/support/cassettes/GroupAssignment/validation_methods_that_call_API/_starter_code_repository_is_template/is_called_if_starter_code_repo_id_is_changed.json
Labels: fix :hammer_and_wrench:

#2284 Log LMS import errors
  app/controllers/orgs/rosters_controller/lti_dependency.rb
  spec/controllers/orgs/rosters_controller_spec.rb
  spec/support/cassettes/Orgs_RostersController/POST_create/when_there_is_an_lti_configuration_present/failbot/reports_when_there_is_an_error/successfully_when_errors_occur_.json
  spec/support/cassettes/Orgs_RostersController/POST_create/when_there_is_an_lti_configuration_present/failbot/when_there_are_no_errors/does_not_report.json
  spec/support/cassettes/Orgs_RostersController/POST_create/when_there_is_an_lti_configuration_present/failbot_reports_when_there_is_an_error/successfully.json
Labels: LMS Integration :school:

#2288 Update Canvas help page
  docs/setup-canvas.md
Labels: Help Docs :page_facing_up:

#2290 Use form helper instead of HTML for starter code repo field
  app/views/assignments/_assignment_form_options.html.erb
  app/views/group_assignments/_group_assignment_form_options.html.erb
Labels: Tech Debt 🧱

#2276 Remove roster entries from deleted rosters
  lib/tasks/remove_deleted_roster_entries.rake
Labels: student roster :man_student: :woman_student:

#2296 Remove one-time rake jobs
  lib/tasks/backfill_lms_user_ids.rake
  lib/tasks/remove_deleted_roster_entries.rake
Labels: maintenance 🛠

#2327 Adding unzip of gzip responses
  Gemfile
  Gemfile.lock
  lib/github_classroom/lti/mixins/request_signing.rb
Labels: LMS Integration :school:

#2330 Remove unnecessary import for github-markdown-css
  app/assets/stylesheets/application.scss
Labels: deploy:queued
