Repository education/classroom, pull requests merged in 2019-07, with the labels that each got.

#1911 Create LTI Auth Client
  Gemfile
  Gemfile.lock
  app/controllers/application_controller/authentication_dependency.rb
  app/controllers/application_controller/feature_flags_dependency.rb
  app/controllers/sessions_controller.rb
  config/initializers/omniauth.rb
  config/routes.rb
  lib/omniauth/strategies/lti.rb
  spec/integration/lti_launch_spec.rb
  spec/support/cassettes/LTI_launch/sessions_lti_launch/authenticated_request/has_access_to_a_logged_in_user.json
  spec/support/cassettes/LTI_launch/sessions_lti_launch/authenticated_request/has_lti_uid_set_on_session.json
  spec/support/cassettes/LTI_launch/sessions_lti_launch/authenticated_request/redirects_to_sessions_lti_callback.json
  spec/support/omniauth.rb
  vendor/cache/aes_key_wrap-1.0.1.gem
  vendor/cache/bindata-2.4.4.gem
  vendor/cache/faraday_middleware-0.13.1.gem
  vendor/cache/ims-lti-2.2.3.gem
  vendor/cache/json-jwt-1.10.2.gem
  vendor/cache/simple_oauth-0.3.1.gem
Labels: enhancement :sparkles:

#1947 Initial model for LTI Configuration
  app/models/lti_configuration.rb
  spec/models/lti_configuration_spec.rb
Labels: LMS Integration :school:

#1949 Create GitHubClassroom::LtiMessageStore utilty class
  config/initializers/lti_message_store.rb
  lib/github_classroom/lti_message_store.rb
  spec/lib/github_classroom/lti_message_store_spec.rb
Labels: LMS Integration :school:

#1961 Add "has_one" relationship on organization to lti_configuration
  app/models/organization.rb
  spec/models/organization_spec.rb
Labels: LMS Integration :school:

#1959 Persist LTI identifying credentials for user session upon launch
  app/controllers/sessions_controller.rb
  app/models/lti_configuration.rb
  config/initializers/lti_message_store.rb
  config/initializers/omniauth.rb
  config/routes.rb
  lib/github_classroom/lti_message_store.rb
  lib/omniauth/strategies/lti.rb
  spec/factories.rb
  spec/integration/lti_launch_spec.rb
  spec/lib/github_classroom/lti_message_store_spec.rb
  spec/support/cassettes/LTI_launch/sessions_lti_launch/authenticated_request/has_access_to_a_logged_in_user.json
  spec/support/cassettes/LTI_launch/sessions_lti_launch/authenticated_request/has_lti_uid_set_on_session.json
  spec/support/cassettes/LTI_launch/sessions_lti_launch/authenticated_request/redirects_to_linked_organization.json
  spec/support/cassettes/LTI_launch/sessions_lti_launch/authenticated_request/redirects_to_sessions_lti_callback.json
  spec/support/omniauth.rb
Labels: LMS Integration :school:

#1935 LTI integration User Interface
  app/controllers/application_controller/feature_flags_dependency.rb
  app/controllers/orgs/lti_configurations_controller.rb
  app/views/organizations/_side_menu.html.erb
  app/views/orgs/lti_configurations/info.html.erb
  app/views/orgs/lti_configurations/show.html.erb
  config/routes.rb
  spec/controllers/orgs/lti_configurations_controller_spec.rb
  spec/support/cassettes/Orgs_LtiConfigurationsController/GET_info/with_flipper_disabled/returns_not_found.json
  spec/support/cassettes/Orgs_LtiConfigurationsController/GET_info/with_flipper_enabled/renders_info_template.json
  spec/support/cassettes/Orgs_LtiConfigurationsController/GET_info/with_flipper_enabled/returns_success_status.json
  spec/support/cassettes/Orgs_LtiConfigurationsController/GET_show/with_flipper_disabled/returns_not_found.json
  spec/support/cassettes/Orgs_LtiConfigurationsController/GET_show/with_flipper_enabled/with_lti_configuration_present/renders_show_template.json
  spec/support/cassettes/Orgs_LtiConfigurationsController/GET_show/with_flipper_enabled/with_lti_configuration_present/returns_success_status.json
  spec/support/cassettes/Orgs_LtiConfigurationsController/GET_show/with_flipper_enabled/with_no_existing_lti_configuration/redirects_to_info.json
Labels: LMS Integration :school:

#1979 Migration: Change "lms_link" column to allow null
  db/migrate/20190710202356_change_lms_link.rb
  db/schema.rb
Labels: LMS Integration :school:

#1991 When Google Classroom Integration Exists Show Sync Modal
  app/views/orgs/rosters/_new_student_modal.html.erb
Labels: Google Classroom, fix :hammer_and_wrench:

#1990 Implement LtiConfigurations Controller
  app/controllers/orgs/lti_configurations_controller.rb
  app/models/organization.rb
  app/views/organizations/_side_menu.html.erb
  app/views/orgs/lti_configurations/_edit_form.html.erb
  app/views/orgs/lti_configurations/edit.html.erb
  app/views/orgs/lti_configurations/new.html.erb
  app/views/orgs/lti_configurations/show.html.erb
  config/routes.rb
  spec/controllers/orgs/lti_configurations_controller_spec.rb
  spec/support/cassettes/Orgs_LtiConfigurationsController/DELETE_destroy/with_flipper_disabled/does_not_create_lti_configuration.json
  spec/support/cassettes/Orgs_LtiConfigurationsController/DELETE_destroy/with_flipper_enabled/with_lti_configuration_present/deletes_lti_configuration.json
  spec/support/cassettes/Orgs_LtiConfigurationsController/GET_new/with_flipper_disabled/returns_not_found.json
  spec/support/cassettes/Orgs_LtiConfigurationsController/GET_new/with_flipper_enabled/renders_new_template.json
  spec/support/cassettes/Orgs_LtiConfigurationsController/GET_new/with_flipper_enabled/returns_success_status.json
  spec/support/cassettes/Orgs_LtiConfigurationsController/GET_show/with_flipper_enabled/with_no_existing_lti_configuration/redirects_to_new.json
  spec/support/cassettes/Orgs_LtiConfigurationsController/PATCH_update/with_flipper_disabled/returns_a_not_found.json
  spec/support/cassettes/Orgs_LtiConfigurationsController/PATCH_update/with_flipper_on/with_existing_lti_configuration/does_not_update_with_new_LMS_url.json
  spec/support/cassettes/Orgs_LtiConfigurationsController/PATCH_update/with_flipper_on/with_existing_lti_configuration/updates_with_new_LMS_url.json
  spec/support/cassettes/Orgs_LtiConfigurationsController/PATCH_update/with_flipper_on/with_no_existing_lti_configuration/does_not_update_or_create.json
  spec/support/cassettes/Orgs_LtiConfigurationsController/PATCH_update/with_flipper_on/with_no_existing_lti_configuration/updates_with_new_LMS_url.json
  spec/support/cassettes/Orgs_LtiConfigurationsController/POST_create/with_flipper_disabled/does_not_create_lti_configuration.json
  spec/support/cassettes/Orgs_LtiConfigurationsController/POST_create/with_flipper_enabled/creates_lti_configuration.json
  spec/support/cassettes/Orgs_LtiConfigurationsController/POST_create/with_flipper_enabled/does_not_create_a_configuration_if_one_exists.json
  spec/support/cassettes/Orgs_LtiConfigurationsController/POST_create/with_flipper_enabled/with_existing_configuration/does_not_create_a_configuration_if_one_exists.json
Labels: LMS Integration :school:

#1997 Allow roster entries to be made after unlinking from Google Classroom
  app/views/orgs/rosters/_new_student_modal.html.erb
Labels: Google Classroom, fix :hammer_and_wrench:

#1992 Consolidate LTI Services
  app/controllers/sessions_controller.rb
  config/initializers/lti_message_store.rb
  lib/github_classroom/lti/message_store.rb
  lib/github_classroom/lti_message_store.rb
  spec/lib/github_classroom/lti/lti_message_store_spec.rb
Labels: LMS Integration :school:

#2009 Fix "lti_launch" flag
  app/controllers/application_controller/feature_flags_dependency.rb
Labels: LMS Integration :school:

#2014 Update README with Google environment variables
  README.md
Labels: Google Classroom

#1998 Implement LTI's auto-configure LMS capabilities
  app/controllers/orgs/lti_configurations_controller.rb
  app/views/orgs/lti_configurations/show.html.erb
  config/routes.rb
  lib/github_classroom/lti/configuration_builder.rb
  spec/controllers/orgs/lti_configurations_controller_spec.rb
  spec/lib/github_classroom/lti/configuration_builder_spec.rb
  spec/support/cassettes/Orgs_LtiConfigurationsController/GET_autoconfigure/with_flipper_on/with_existing_lti_configuration/returns_an_xml_configuration.json
Labels: LMS Integration :school:

#2020 Add context_membership_url to lti_configurations table
  db/migrate/20190716211230_add_column_to_lti_configurations.rb
  db/schema.rb
Labels: LMS Integration :school:

#2013 Create LTI::MembershipService
  Gemfile
  Gemfile.lock
  lib/github_classroom/lti/membership_service.rb
  lib/github_classroom/lti/mixins/request_signing.rb
  spec/lib/github_classroom/lti/membership_service_spec.rb
  spec/support/cassettes/GitHubClassroom_LTI_MembershipService/membership/invalid_authentication/cannot_get_members.json
  spec/support/cassettes/GitHubClassroom_LTI_MembershipService/membership/valid_authentication/gets_all_membership.json
  spec/support/cassettes/GitHubClassroom_LTI_MembershipService/membership/valid_authentication/gets_only_instructors.json
  spec/support/cassettes/GitHubClassroom_LTI_MembershipService/membership/valid_authentication/gets_only_students.json
  vendor/cache/oauth-0.5.4.gem
Labels: LMS Integration :school:

#2021 Ensure there is no existing roster when adding integration
  app/controllers/orgs/lti_configurations_controller.rb
  app/controllers/orgs/rosters_controller.rb
  spec/controllers/orgs/lti_configurations_controller_spec.rb
  spec/controllers/orgs/rosters_controller_spec.rb
  spec/support/cassettes/Orgs_LtiConfigurationsController/POST_create/with_flipper_enabled/with_an_existing_roster/alerts_user_that_there_is_an_existing_roster.json
  spec/support/cassettes/Orgs_RostersController/GET_select_google_classroom/with_student_identifier_flipper_enabled/with_google_classroom_flipper_enabled/when_there_is_an_existing_roster/alerts_user_that_there_is_an_existing_roster.json
Labels: Google Classroom, LMS Integration :school:

#2022 Student identifier default for sort
  app/models/roster_entry.rb
Labels: assignments :bookmark_tabs:, fix :hammer_and_wrench:

#2018 Limit teachers to only one integration
  app/controllers/orgs/lti_configurations_controller.rb
  app/controllers/orgs/rosters_controller.rb
  app/views/orgs/rosters/_new_student_modal.html.erb
  app/views/orgs/rosters/new.html.erb
  spec/controllers/orgs/lti_configurations_controller_spec.rb
  spec/controllers/orgs/rosters_controller_spec.rb
  spec/support/cassettes/Orgs_LtiConfigurationsController/GET_info/with_flipper_enabled/with_existing_google_classrom/alerts_user_about_existing_configuration.json
  spec/support/cassettes/Orgs_LtiConfigurationsController/GET_new/with_flipper_enabled/with_existing_google_classrom/alerts_user_about_existing_configuration.json
  spec/support/cassettes/Orgs_LtiConfigurationsController/POST_create/with_flipper_enabled/with_existing_google_classrom/alerts_user_about_existing_configuration.json
  spec/support/cassettes/Orgs_RostersController/GET_search_google_classroom/with_student_identifier_flipper_enabled/with_google_classroom_flipper_enabled/when_user_is_authorized_with_google/when_there_is_an_existing_lti_configuration/alerts_user_that_there_is_an_exisiting_config.json
  spec/support/cassettes/Orgs_RostersController/GET_select_google_classroom/with_student_identifier_flipper_enabled/with_google_classroom_flipper_enabled/when_there_is_an_existing_lti_configuration/alerts_user_that_there_is_an_exisiting_config.json
  spec/support/cassettes/Orgs_RostersController/PATCH_import_from_google_classroom/with_student_identifier_flipper_enabled/with_google_classroom_flipper_enabled/when_user_is_authorized_with_google/when_there_is_an_existing_lti_configuration/alerts_user_that_there_is_an_exisiting_config.json
Labels: Google Classroom, LMS Integration :school:

#1982 Search by GitHub attributes on non-roster AssignmentRepos
  app/controllers/assignments_controller.rb
  app/controllers/group_assignments_controller.rb
  app/models/assignment_repo.rb
  app/models/concerns/searchable.rb
  app/models/group_assignment_repo.rb
  app/models/roster_entry.rb
  app/views/assignments/_assignment_roster_list.html.erb
  app/views/assignments/_filterable_assignment_roster_list.html.erb
  app/views/assignments/filter_repos.js.erb
  app/views/assignments/show.html.erb
  spec/models/assignment_repo_spec.rb
  spec/models/group_assignment_repo_spec.rb
  spec/models/roster_entry_spec.rb
  spec/support/cassettes/GroupAssignmentRepo/with_created_objects/is_searchable/filter_by_sort_mode_searches_by_Team_name_.json
Labels: assignments :bookmark_tabs:, enhancement :sparkles:

#2042 Prevent grouping persistence if group assignment validation fails
  app/services/group_assignment_service.rb
  spec/models/group_assignment_spec.rb
Labels: fix :hammer_and_wrench:

#2038 Move google auth to application controller
  app/controllers/application_controller.rb
  app/controllers/application_controller/google_authentication_dependency.rb
  app/controllers/orgs/rosters_controller.rb
Labels: Google Classroom

#2033 LMS Roster Import
  app/controllers/orgs/rosters_controller.rb
  app/controllers/orgs/rosters_controller/lti_dependency.rb
  app/models/lti_configuration.rb
  app/views/organizations/_side_menu.html.erb
  app/views/orgs/lti_configurations/show.html.erb
  app/views/orgs/rosters/_new_student_modal.html.erb
  app/views/orgs/rosters/_select_identifier_modal.html.erb
  app/views/orgs/rosters/import_from_lms.html.erb
  app/views/orgs/rosters/import_from_lms.js.erb
  app/views/orgs/rosters/new.html.erb
  app/views/orgs/rosters/show.html.erb
  config/routes.rb
  lib/github_classroom/lti/membership_service.rb
  spec/controllers/orgs/rosters_controller_spec.rb
  spec/models/lti_configuration_spec.rb
  spec/support/cassettes/Orgs_RostersController/GET_import_lms_roster/with_lti_launch_disabled/404s.json
  spec/support/cassettes/Orgs_RostersController/GET_import_lms_roster/with_lti_launch_enabled/with_existing_LMS/with_context_membership_url/fetching_roster_fails/format_html_presents_an_error_message_to_the_user.json
  spec/support/cassettes/Orgs_RostersController/GET_import_lms_roster/with_lti_launch_enabled/with_existing_LMS/with_context_membership_url/fetching_roster_fails/format_js_presents_an_error_message_to_the_user.json
  spec/support/cassettes/Orgs_RostersController/GET_import_lms_roster/with_lti_launch_enabled/with_existing_LMS/with_context_membership_url/fetching_roster_succeeds/format_html_succeeds.json
  spec/support/cassettes/Orgs_RostersController/GET_import_lms_roster/with_lti_launch_enabled/with_existing_LMS/with_context_membership_url/fetching_roster_succeeds/format_js_succeeds.json
  spec/support/cassettes/Orgs_RostersController/GET_import_lms_roster/with_lti_launch_enabled/with_existing_LMS/without_context_membership_service_url/format_html_presents_an_error_message_to_the_user.json
  spec/support/cassettes/Orgs_RostersController/GET_import_lms_roster/with_lti_launch_enabled/with_existing_LMS/without_context_membership_service_url/format_js_presents_an_error_message_to_the_user.json
  spec/support/cassettes/Orgs_RostersController/GET_import_lms_roster/with_lti_launch_enabled/with_no_existing_LMS/Redirects_to_new_LTI_configuration_page.json
Labels: LMS Integration :school:

#2041 Add type column to LMS Configuration
  app/models/lti_configuration.rb
  db/migrate/20190718211229_lms_type.rb
  db/schema.rb
  spec/models/lti_configuration_spec.rb
Labels: LMS Integration :school:

#2056 Specify LMS Platform on Creation
  app/controllers/orgs/lti_configurations_controller.rb
  app/helpers/lti_configuration_helper.rb
  app/models/lti_configuration.rb
  app/views/organizations/_side_menu.html.erb
  app/views/orgs/lti_configurations/_edit_form.html.erb
  app/views/orgs/lti_configurations/_form.html.erb
  app/views/orgs/lti_configurations/edit.html.erb
  app/views/orgs/lti_configurations/info.html.erb
  app/views/orgs/lti_configurations/new.html.erb
  app/views/orgs/lti_configurations/show.html.erb
  config/routes.rb
  spec/controllers/orgs/lti_configurations_controller_spec.rb
  spec/factories.rb
  spec/support/cassettes/Orgs_LtiConfigurationsController/GET_info/with_flipper_enabled/renders_new_template.json
  spec/support/cassettes/Orgs_LtiConfigurationsController/POST_create/with_flipper_enabled/creates_lti_configuration_if_lms_type_is_set.json
  spec/support/cassettes/Orgs_LtiConfigurationsController/POST_create/with_flipper_enabled/redirects_to_new_if_lms_type_is_unset.json
Labels: LMS Integration :school:, ui :art:

#2055 Remove navigation icons from the header
  app/assets/stylesheets/layout.scss
  app/views/layouts/stafftools.html.erb
  app/views/shared/_header.html.erb
  config/locales/views/shared/en.yml
Labels: ui :art:

#2071 LMS platform specific language
  app/controllers/orgs/lti_configurations_controller.rb
  app/controllers/orgs/rosters_controller/lti_dependency.rb
  app/models/lti_configuration.rb
  app/views/orgs/lti_configurations/_form.html.erb
  app/views/orgs/lti_configurations/info.html.erb
  app/views/orgs/lti_configurations/new.html.erb
Labels: LMS Integration :school:, ui :art:

#2067 Update local pinned postgres version from 9.4 to 10
  Brewfile
  script/bootstrap
Labels: No Op, maintenance 🛠

#2078 Use Octokit instead of directly calling API for template-related calls
  app/models/github_repository.rb
  spec/models/assignment_repo/creator_spec.rb
  spec/models/assignment_spec.rb
  spec/models/github_repository_spec.rb
  spec/models/group_assignment_repo/creator_spec.rb
  spec/models/group_assignment_spec.rb
  spec/support/cassettes/Assignment/_starter_code_repository_is_template/assignment_is_not_using_template_repos_to_import/does_not_raise_error_when_not_using_starter_code.json
  spec/support/cassettes/Assignment/_starter_code_repository_is_template/assignment_is_not_using_template_repos_to_import/does_not_raise_error_when_using_importer.json
  spec/support/cassettes/Assignment/_starter_code_repository_is_template/assignment_is_using_template_repos_to_import/does_not_raise_an_error_when_starter_code_repo_is_a_template_repo.json
  spec/support/cassettes/Assignment/_starter_code_repository_is_template/assignment_is_using_template_repos_to_import/raises_an_error_when_starter_code_repository_is_not_a_template_repo.json
  spec/support/cassettes/Assignment/_starter_code_repository_not_empty/does_not_raise_an_error_when_starter_code_repository_is_not_empty.json
  spec/support/cassettes/Assignment/_starter_code_repository_not_empty/raises_an_error_when_starter_code_repository_is_empty.json
  spec/support/cassettes/AssignmentRepo_Creator/_perform/successful_creation/using_template_repos/creates_an_AssignmentRepo_as_a_member.json
  spec/support/cassettes/AssignmentRepo_Creator/_perform/successful_creation/using_template_repos/creates_an_AssignmentRepo_as_an_outside_collaborator.json
  spec/support/cassettes/AssignmentRepo_Creator/_perform/successful_creation/using_template_repos/github_repository_with_the_same_name_already_exists/new_repository_name_has_expected_suffix.json
  spec/support/cassettes/AssignmentRepo_Creator/_perform/successful_creation/using_template_repos/tracks_create_success_stat.json
  spec/support/cassettes/AssignmentRepo_Creator/_perform/successful_creation/using_template_repos/tracks_the_how_long_it_too_to_be_created.json
  spec/support/cassettes/GitHubRepository/instance_methods/_template_/repository_is_a_template/returns_true.json
  spec/support/cassettes/GitHubRepository/instance_methods/_template_/repository_is_not_a_template/returns_false.json
  spec/support/cassettes/GroupAssignment/_starter_code_repository_is_template/group_assignment_is_not_using_template_repos_to_import/does_not_raise_error_when_not_using_starter_code.json
  spec/support/cassettes/GroupAssignment/_starter_code_repository_is_template/group_assignment_is_not_using_template_repos_to_import/does_not_raise_error_when_using_importer.json
  spec/support/cassettes/GroupAssignment/_starter_code_repository_is_template/group_assignment_is_using_template_repos_to_import/does_not_raise_an_error_when_starter_code_repo_is_a_template_repo.json
  spec/support/cassettes/GroupAssignment/_starter_code_repository_is_template/group_assignment_is_using_template_repos_to_import/raises_an_error_when_starter_code_repository_is_not_a_template_repo.json
  spec/support/cassettes/GroupAssignmentRepo_Creator/_perform/successful_creation/with_template_repos/broadcasts/creating_repo.json
  spec/support/cassettes/GroupAssignmentRepo_Creator/_perform/successful_creation/with_template_repos/creates_a_GroupAssignmentRepo_with_a_group.json
  spec/support/cassettes/GroupAssignmentRepo_Creator/_perform/successful_creation/with_template_repos/github_repository_with_the_same_name_already_exists/new_repository_name_has_expected_suffix.json
  spec/support/cassettes/GroupAssignmentRepo_Creator/_perform/successful_creation/with_template_repos/tracks_create_success_stat.json
  spec/support/cassettes/GroupAssignmentRepo_Creator/_perform/successful_creation/with_template_repos/tracks_the_how_long_it_too_to_be_created.json
Labels: Tech Debt 🧱

#2079 Fix flakey LTI test
  spec/controllers/orgs/rosters_controller_spec.rb
Labels: fix :hammer_and_wrench:

#2040 Update UI for Organization Navigation Banner and Settings
  app/assets/stylesheets/components/buttons.scss
  app/assets/stylesheets/layout.scss
  app/views/layouts/application.html.erb
  app/views/organizations/_navigation.html.erb
  app/views/organizations/_organization_banner.html.erb
  app/views/organizations/_organization_invitation_banner.html.erb
  app/views/organizations/edit.html.erb
  app/views/organizations/invitation.html.erb
  app/views/orgs/lti_configurations/new.html.erb
  app/views/orgs/lti_configurations/show.html.erb
  app/views/orgs/rosters/show.html.erb
  app/views/shared/_footer.html.erb
Labels: ui :art:

#2047 Update Classroom creation form UI
  app/views/organizations/_disabled_organization_select.html.erb
  app/views/organizations/_invite_users.html.erb
  app/views/organizations/_organization_select.html.erb
  app/views/organizations/new.html.erb
  app/views/organizations/setup.html.erb
  app/views/orgs/rosters/new.html.erb
Labels: ui :art:

#2043 Update create assignment (and group assignment) forms
  app/view_models/form_view.rb
  app/views/assignments/_assignment_form_options.html.erb
  app/views/assignments/new.html.erb
  app/views/group_assignments/_banner.html.erb
  app/views/group_assignments/_group_assignment_form_options.html.erb
  app/views/group_assignments/_navigation.html.erb
  app/views/group_assignments/new.html.erb
  app/views/organizations/new_assignment.html.erb
  app/views/shared/_unlimited_free_private_repositories_banner.html.erb
  spec/view_models/form_view_spec.rb
Labels: ui :art:

#2077 Refactor repository creation with templates
  app/models/assignment_repo/creator.rb
  app/models/github_organization.rb
  app/models/group_assignment_repo/creator.rb
  spec/models/github_organization_spec.rb
  spec/support/cassettes/GitHubOrganization/_create_repository_from_template/successfully_creates_a_github_repository_for_the_organization_using_a_template.json
Labels: Tech Debt 🧱

#2087 Move Organization updating to new Organization::Editor class
  app/controllers/organizations_controller.rb
  app/models/organization/editor.rb
  spec/models/organization/editor_spec.rb
Labels: enhancement :sparkles:

#2094 Fix download repos button
  app/views/assignments/show.html.erb
  app/views/group_assignments/show.html.erb
Labels: fix :hammer_and_wrench:

#2089 Unify LMS/Google Classroom Creation Flow
  app/assets/images/blackboard-logo.png
  app/assets/images/brightspace-logo.png
  app/assets/images/canvas-logo.png
  app/assets/images/moodle-logo.png
  app/assets/images/other-logo.png
  app/assets/images/sakai-logo.png
  app/assets/images/schoology-logo.png
  app/controllers/organizations_controller.rb
  app/controllers/orgs/lti_configurations_controller.rb
  app/controllers/orgs/rosters_controller/lti_dependency.rb
  app/controllers/sessions_controller.rb
  app/views/organizations/_invite_users.html.erb
  app/views/organizations/_side_menu.html.erb
  app/views/organizations/edit.html.erb
  app/views/organizations/link_lms.html.erb
  app/views/orgs/lti_configurations/show.html.erb
  app/views/orgs/rosters/_new_student_modal.html.erb
  app/views/orgs/rosters/new.html.erb
  app/views/orgs/rosters/show.html.erb
  config/routes.rb
  spec/controllers/organizations_controller_spec.rb
  spec/controllers/orgs/lti_configurations_controller_spec.rb
  spec/controllers/orgs/rosters_controller_spec.rb
  spec/support/cassettes/OrganizationsController/GET_link_lms/with_lti_launch_enabled/renders_the_LMS_selection_page.json
  spec/support/cassettes/OrganizationsController/GET_link_lms/without_lti_launch_disabled/returns_not_found.json
  spec/support/cassettes/Orgs_RostersController/GET_import_lms_roster/with_lti_launch_enabled/with_no_existing_LMS/Redirects_to_link_LTI_configuration_page.json
  spec/support/cassettes/Orgs_RostersController/GET_import_lms_roster/with_lti_launch_enabled/with_no_existing_LMS/Redirects_to_new_LTI_configuration_page.json
Labels: Google Classroom, LMS Integration :school:, ui :art:

#2097 Roster import UI tweaks
  app/controllers/organizations_controller.rb
  app/views/orgs/rosters/_new_student_modal.html.erb
  app/views/orgs/rosters/_sync_google_roster_modal.html.erb
  app/views/orgs/rosters/new.html.erb
  app/views/orgs/rosters/show.html.erb
  spec/controllers/organizations_controller_spec.rb
  spec/support/cassettes/OrganizationsController/GET_link_lms/with_google_classroom_disabled/renders_the_LMS_selection_page.json
  spec/support/cassettes/OrganizationsController/GET_link_lms/with_lti_launch_or_google_classroom_disabled/returns_not_found.json
Labels: Google Classroom, LMS Integration :school:, ui :art:

#2100 Don't restrict LtiConfigurationsController#autoconfigure to feature flag
  app/controllers/orgs/lti_configurations_controller.rb
  spec/controllers/orgs/lti_configurations_controller_spec.rb
  spec/support/cassettes/Orgs_LtiConfigurationsController/GET_autoconfigure/with_flipper_on/with_existing_lti_configuration/returns_an_xml_configuration.json
Labels: LMS Integration :school:

#2105 Add feature flag check
  app/views/organizations/edit.html.erb
Labels: Google Classroom, LMS Integration :school:, ui :art:

#2106 Change layout of LMS links
  app/views/organizations/link_lms.html.erb
Labels: Google Classroom, LMS Integration :school:, ui :art:

#2091 Use the GitHubOrganization#create_repository_from_template in unified repo creator
  app/services/create_github_repo_service.rb
  spec/services/create_github_repo_service_spec.rb
  spec/support/cassettes/CreateGitHubRepoService/for_Assignment/_create_github_repository_from_template_/raises_a_Result_Error_if_repository_not_created.json
  spec/support/cassettes/CreateGitHubRepoService/for_Assignment/_create_github_repository_from_template_/sends_a_request_to_GitHubOrganization_create_repository_from_template_with_correct_params.json
  spec/support/cassettes/CreateGitHubRepoService/for_Assignment/_create_github_repository_from_template_/sends_a_request_to_OctoKit_Client_via_assignment_creator_github_client_with_correct_params.json
  spec/support/cassettes/CreateGitHubRepoService/for_Assignment/_perform/successful_creation/with_template_repos/tracks_create_success_stat.json
  spec/support/cassettes/CreateGitHubRepoService/for_Assignment/_perform/successful_creation/with_template_repos/tracks_the_how_long_it_too_to_be_created.json
  spec/support/cassettes/CreateGitHubRepoService/for_GroupAssignment/_create_github_repository_from_template_/raises_a_Result_Error_if_repository_not_created.json
  spec/support/cassettes/CreateGitHubRepoService/for_GroupAssignment/_create_github_repository_from_template_/sends_a_request_to_GitHubOrganization_create_repository_from_template_with_correct_params.json
  spec/support/cassettes/CreateGitHubRepoService/for_GroupAssignment/_create_github_repository_from_template_/sends_a_request_to_OctoKit_Client_via_assignment_creator_github_client_with_correct_params.json
Labels: assignments :bookmark_tabs:

#2104 New Google Classroom Flow
  app/views/organizations/edit.html.erb
  app/views/organizations/link_lms.html.erb
  app/views/orgs/google_classroom_configurations/_google_classroom_collection.html.erb
  app/views/orgs/google_classroom_configurations/index.html.erb
  app/views/orgs/rosters/_sync_google_roster_modal.html.erb
  app/views/orgs/rosters/new.html.erb
  app/views/orgs/rosters/show.html.erb
Labels: Google Classroom, ui :art:

#2099 When accepting a GroupAssignmentInvitation, redirect users to show page if they have not selected a group yet
  app/controllers/group_assignment_invitations_controller.rb
  spec/controllers/group_assignment_invitations_controller_spec.rb
  spec/support/cassettes/GroupAssignmentInvitationsController/GET_accept/user_has_no_group/redirects_to_show_if_user_manually_visits_accept.json
Labels: assignments :bookmark_tabs:

#2117 Add back flag check
  app/views/organizations/_invite_users.html.erb
  app/views/organizations/edit.html.erb
  app/views/organizations/link_lms.html.erb
Labels: bug :beetle:

#2109 Add a 404 if repo not found, when we make API call for classroom-assistant
  app/controllers/api/assignment_repos_controller.rb
  app/controllers/api/group_assignment_repos_controller.rb
  spec/controllers/api/assignment_repos_controller_spec.rb
  spec/controllers/api/group_assignment_repos_controller_spec.rb
  spec/support/cassettes/API_AssignmentReposController/GET_clone_url/returns_404_if_invalid_repository_found.json
  spec/support/cassettes/API_GroupAssignmentReposController/GET_clone_url/returns_404_if_invalid_repository_found.json
  spec/support/cassettes/API_GroupAssignmentReposController/GET_clone_url/returns_json_with_temp_clone_url.json
  spec/support/cassettes/API_GroupAssignmentReposController/GET_clone_url/returns_success.json
  spec/support/cassettes/API_GroupAssignmentReposController/GET_index/returns_correct_attributes_in_group_assignment_repo_serializer.json
  spec/support/cassettes/API_GroupAssignmentReposController/GET_index/returns_success.json
Labels: classroom assistant :desktop_computer:

#2118 Redirect to standalone success view on successful LTI linking
  app/controllers/orgs/lti_configurations_controller.rb
  app/controllers/sessions_controller.rb
  app/views/organizations/edit.html.erb
  app/views/orgs/lti_configurations/complete.html.erb
  config/routes.rb
  db/schema.rb
  spec/controllers/orgs/lti_configurations_controller_spec.rb
  spec/integration/lti_launch_spec.rb
  spec/support/cassettes/LTI_launch/sessions_lti_launch/authenticated_request/redirects_to_linked_organization.json
  spec/support/cassettes/LTI_launch/sessions_lti_launch/authenticated_request/redirects_to_lms_success_page.json
  spec/support/cassettes/Orgs_LtiConfigurationsController/GET_complete/with_flipper_disabled/returns_a_not_found.json
  spec/support/cassettes/Orgs_LtiConfigurationsController/GET_complete/with_flipper_on/with_existing_lti_configuration/with_user_who_is_an_instructor/returns_success_page.json
Labels: LMS Integration :school:, ui :art:

#2114 Refactor LtiConfiguration to use LMS Specific settings
  app/controllers/orgs/lti_configurations_controller.rb
  app/models/lti_configuration.rb
  app/models/lti_configuration/blackboard_settings.rb
  app/models/lti_configuration/brightspace_settings.rb
  app/models/lti_configuration/canvas_settings.rb
  app/models/lti_configuration/generic_settings.rb
  app/models/lti_configuration/moodle_settings.rb
  app/views/orgs/lti_configurations/show.html.erb
  spec/controllers/orgs/lti_configurations_controller_spec.rb
  spec/models/lti_configuration/blackboard_settings_spec.rb
  spec/models/lti_configuration/brightspace_settings_spec.rb
  spec/models/lti_configuration/canvas_settings_spec.rb
  spec/models/lti_configuration/generic_settings_spec.rb
  spec/models/lti_configuration/moodle_settings_spec.rb
Labels: LMS Integration :school:

#2124 Add DataDog metrics to Google Classroom and LMS
  app/controllers/orgs/google_classroom_configurations_controller.rb
  app/controllers/orgs/lti_configurations_controller.rb
  app/controllers/orgs/rosters_controller.rb
  app/controllers/orgs/rosters_controller/lti_dependency.rb
  spec/controllers/orgs/google_classroom_configurations_controller_spec.rb
  spec/controllers/orgs/lti_configurations_controller_spec.rb
  spec/controllers/orgs/rosters_controller_spec.rb
  spec/support/cassettes/Orgs_GoogleClassroomConfigurationsController/_create/with_flipper_on/when_the_user_is_authorized/creates_a_statsd_event.json
  spec/support/cassettes/Orgs_GoogleClassroomConfigurationsController/_create/with_flipper_on/when_the_user_is_authorized/creates_configuration/suceeds.json
  spec/support/cassettes/Orgs_GoogleClassroomConfigurationsController/_create/with_flipper_on/when_the_user_is_authorized/sends_a_statsD.json
  spec/support/cassettes/Orgs_GoogleClassroomConfigurationsController/_destroy/deletes_google_classroom/redirects_or_organization_page.json
  spec/support/cassettes/Orgs_GoogleClassroomConfigurationsController/_destroy/deletes_google_classroom/succeeds.json
  spec/support/cassettes/Orgs_GoogleClassroomConfigurationsController/_destroy/sends_statsd/succeeds.json
  spec/support/cassettes/Orgs_LtiConfigurationsController/DELETE_destroy/with_flipper_enabled/sends_statsd.json
  spec/support/cassettes/Orgs_LtiConfigurationsController/DELETE_destroy/with_flipper_enabled/with_lti_configuration_present/sends_statsd.json
  spec/support/cassettes/Orgs_LtiConfigurationsController/POST_create/with_flipper_enabled/sends_statsd.json
  spec/support/cassettes/Orgs_RostersController/GET_import_lms_roster/with_lti_launch_enabled/with_existing_LMS/with_context_membership_url/fetching_roster_succeeds/sends_statsd.json
  spec/support/cassettes/Orgs_RostersController/PATCH_import_from_google_classroom/with_google_classroom_flipper_enabled/when_google_classroom_course_is_linked/when_user_is_authorized_with_google/when_course_has_multiple_students/when_organization_has_no_roster/sends_statsd.json
  spec/support/cassettes/Orgs_RostersController/PATCH_import_from_google_classroom/with_google_classroom_flipper_enabled/when_google_classroom_course_is_linked/when_user_is_authorized_with_google/when_course_has_multiple_students/when_organization_has_no_roster/when_students_are_fetched_succesfully/sends_statsd.json
Labels: Google Classroom, LMS Integration :school:

#2130 Add user, org, and repo context to template error reporting
  app/models/assignment_repo/creator.rb
  app/models/group_assignment_repo/creator.rb
  app/services/create_github_repo_service.rb
  spec/models/assignment_repo/creator_spec.rb
  spec/models/group_assignment_repo/creator_spec.rb
  spec/services/create_github_repo_service_spec.rb
  spec/support/cassettes/AssignmentRepo_Creator/_perform/successful_creation/using_template_repos/failure/Failbot_report_contains_the_user_repository_and_organization_info.json
  spec/support/cassettes/AssignmentRepo_Creator/_perform/successful_creation/using_template_repos/failure/reports_error_to_Failbot.json
  spec/support/cassettes/CreateGitHubRepoService/for_Assignment/_perform/successful_creation/with_template_repos/failure/reports_collaborator_github_repo_and_organization_info_to_Failbot.json
  spec/support/cassettes/CreateGitHubRepoService/for_Assignment/_perform/successful_creation/with_template_repos/failure/reports_error_to_Failbot.json
  spec/support/cassettes/GroupAssignmentRepo_Creator/_perform/successful_creation/with_template_repos/failure/Failbot_report_contains_the_repository_github_team_and_organization_info.json
  spec/support/cassettes/GroupAssignmentRepo_Creator/_perform/successful_creation/with_template_repos/failure/reports_error_to_Failbot.json
Labels: enhancement :sparkles:

#2120 Fix Google Authentication
  app/controllers/orgs/google_classroom_configurations_controller.rb
  spec/controllers/orgs/google_classroom_configurations_controller_spec.rb
  spec/support/cassettes/Orgs_GoogleClassroomConfigurationsController/_index/with_flipper_on/when_the_user_is_authorized/succeeds.json
  spec/support/cassettes/Orgs_GoogleClassroomConfigurationsController/_index/with_flipper_on/when_the_user_is_authorized/when_there_is_an_error_fetching_classes/sets_error_message.json
Labels: Google Classroom, bug :beetle:

#2134 Failbot tests consider multiple error reports
  spec/models/assignment_repo/creator_spec.rb
  spec/models/group_assignment_repo/creator_spec.rb
  spec/services/create_github_repo_service_spec.rb
Labels: fix :hammer_and_wrench:

#2137 Report all API errors to Haystack with option to disable
  app/models/assignment_repo/creator.rb
  app/models/github_organization.rb
  app/models/group_assignment_repo/creator.rb
  app/services/create_github_repo_service.rb
  lib/github/errors.rb
  spec/lib/github/errors_spec.rb
Labels: enhancement :sparkles:
