Repository education/classroom, pull requests merged in 2019-06, with the labels that each got.

#1852 Fix disabled Download Repositories button for assignments with rosters
  app/controllers/assignments_controller.rb
Labels: fix :hammer_and_wrench:

#1838 Show Repo URL when created (while still importing) [Group Assignment Setup]
  app/jobs/group_assignment_repo/create_github_repository_job.rb
  spec/jobs/group_assignment_repo/create_github_repository_job_spec.rb
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/invalid_invitation_status/returns_early_when_invitation_status_is_accepted.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/invalid_invitation_status/returns_early_when_invitation_status_is_creating_repo.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/invalid_invitation_status/returns_early_when_invitation_status_is_errored_creating_repo.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/invalid_invitation_status/returns_early_when_invitation_status_is_errored_importing_starter_code.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/invalid_invitation_status/returns_early_when_invitation_status_is_importing_starter_code.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/invalid_invitation_status/returns_early_when_invitation_status_is_unaccepted.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/context_no_starter_code/successful_creation/added_the_team_to_the_repository.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/context_no_starter_code/successful_creation/broadcasts/completed.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/context_no_starter_code/successful_creation/broadcasts/creating_repo.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/context_no_starter_code/successful_creation/changes_the_invite_status_to_completed.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/context_no_starter_code/successful_creation/created_a_GitHub_repository.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/context_no_starter_code/successful_creation/datadog_stats/tracks_create_success.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/context_no_starter_code/successful_creation/datadog_stats/tracks_elapsed_time.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/context_no_starter_code/successful_creation/did_not_start_a_source_import.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/context_no_starter_code/successful_creation/group_assignment_repo_not_nil.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/context_no_starter_code/successful_creation/has_the_same_group.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/context_no_starter_code/successful_creation/is_the_same_assignment.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/creation_failure/fails_to_add_the_team_to_the_repository/broadcasts/creating_repo.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/creation_failure/fails_to_add_the_team_to_the_repository/broadcasts/errored_creating_repo.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/creation_failure/fails_to_add_the_team_to_the_repository/perform_after/logs_error.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/creation_failure/fails_to_add_the_team_to_the_repository/perform_after/tracks_create_fail.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/creation_failure/fails_to_add_the_team_to_the_repository/perform_before/changes_invite_status_to_be_errored_creating_repo.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/creation_failure/fails_to_add_the_team_to_the_repository/perform_before/doesn_t_create_a_GroupAssignmentRepo.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/creation_failure/fails_to_create_a_GitHub_repo/broadcasts/creating_repo.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/creation_failure/fails_to_create_a_GitHub_repo/broadcasts/errored_creating_repo.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/creation_failure/fails_to_create_a_GitHub_repo/perform_after/logs_error.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/creation_failure/fails_to_create_a_GitHub_repo/perform_after/tracks_create_fail.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/creation_failure/fails_to_create_a_GitHub_repo/perform_before/changes_invite_status_to_be_errored_creating_repo.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/creation_failure/fails_to_create_a_GitHub_repo/perform_before/doesn_t_create_a_GroupAssignmentRepo.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/creation_failure/fails_to_save_the_record/broadcasts/creating_repo.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/creation_failure/fails_to_save_the_record/broadcasts/errored_creating_repo.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/creation_failure/fails_to_save_the_record/perform_after/logs_error.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/creation_failure/fails_to_save_the_record/perform_after/tracks_create_fail.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/creation_failure/fails_to_save_the_record/perform_before/changes_invite_status_to_be_errored_creating_repo.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/creation_failure/fails_to_save_the_record/perform_before/doesn_t_create_a_GroupAssignmentRepo.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/creation_failure/fails_to_start_a_source_import/broadcasts/creating_repo.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/creation_failure/fails_to_start_a_source_import/broadcasts/errored_creating_repo.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/creation_failure/fails_to_start_a_source_import/perform_after/logs_error.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/creation_failure/fails_to_start_a_source_import/perform_after/tracks_create_fail.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/creation_failure/fails_to_start_a_source_import/perform_before/changes_invite_status_to_be_errored_creating_repo.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/creation_failure/fails_to_start_a_source_import/perform_before/doesn_t_create_a_GroupAssignmentRepo.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/creation_failure/positive_retries/fails_and_automatically_retries.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/creation_failure/positive_retries/fails_and_puts_invite_status_in_state_to_retry.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/successful_creation/added_the_team_to_the_repository.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/successful_creation/broadcasts/creating_repo.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/successful_creation/broadcasts/importing_starter_code.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/successful_creation/changes_the_invite_status_to_importing_starter_code.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/successful_creation/created_a_GitHub_repository.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/successful_creation/datadog_stats/tracks_create_success_and_import_started.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/successful_creation/datadog_stats/tracks_elapsed_time.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/successful_creation/group_assignment_repo_not_nil.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/successful_creation/has_the_same_group.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/successful_creation/is_the_same_assignment.json
  spec/support/cassettes/GroupAssignmentRepo_CreateGitHubRepositoryJob/with_created_objects/valid_invitation_status/successful_creation/started_a_source_import.json
Labels: enhancement :sparkles:, repository setup :package:

#1849 Removed usage of is_webhook_enabled
  app/views/stafftools/organizations/show.html.erb
  spec/models/organization_spec.rb
Labels: Tech Debt 🧱

#1848 Removed PingEventJob and it's assocated files
  app/jobs/ping_event_job.rb
  lib/github/web_hook.rb
  spec/fixtures/files/webhook_events/ping.json
  spec/jobs/ping_event_job_spec.rb
Labels: Tech Debt 🧱

#1850 Remove usage of Organization's `webhook_id`
  app/models/organization.rb
  app/models/organization/creator.rb
  app/views/stafftools/organizations/show.html.erb
  lib/tasks/organization_webhook_backfill.rake
  spec/factories.rb
  spec/models/organization/creator_spec.rb
  spec/models/organization_spec.rb
  spec/support/cassettes/Organization_Creator/_perform/successful_creation/no_classrooms_already_exist_on_the_same_organization/creates_an_Organization_with_a_webhook_id.json
Labels: Tech Debt 🧱

#1853 Remove webhook_id and is_webhook_enabled columns from Organization
  db/migrate/20190601200321_remove_webhook_id_and_is_webhook_active_from_organization.rb
  db/schema.rb
Labels: Tech Debt 🧱

#1854 Button to ensure webhook is active
  app/controllers/stafftools/organizations_controller.rb
  app/views/stafftools/organizations/show.html.erb
  config/locales/views/stafftools/organizations/en.yml
  config/routes.rb
  spec/controllers/stafftools/organizations_controller_spec.rb
  spec/support/cassettes/Stafftools_OrganizationsController/POST_ensure_webhook_is_active/as_an_authorized_user/ensure_webhook_is_active_returns_false/flashes_a_error.json
  spec/support/cassettes/Stafftools_OrganizationsController/POST_ensure_webhook_is_active/as_an_authorized_user/ensure_webhook_is_active_returns_false/redirects.json
  spec/support/cassettes/Stafftools_OrganizationsController/POST_ensure_webhook_is_active/as_an_authorized_user/ensure_webhook_is_active_returns_true/flashes_a_success.json
  spec/support/cassettes/Stafftools_OrganizationsController/POST_ensure_webhook_is_active/as_an_authorized_user/ensure_webhook_is_active_returns_true/redirects.json
  spec/support/cassettes/Stafftools_OrganizationsController/POST_ensure_webhook_is_active/as_an_unauthorized_user/returns_a_404.json
Labels: enhancement :sparkles:

#1856 Add a progress bar to OrganizationWebhookHealthService
  app/services/organization_webhook_health_service.rb
  spec/services/organization_webhook_health_service_spec.rb
Labels: No Op, enhancement :sparkles:

#1861 Update verify_organization_has_private_repos_available with new error message
  app/models/concerns/github_plan.rb
Labels: enhancement :sparkles:

#1863 Add @d12 as CODEOWNER
  CODEOWNERS
Labels: No Op

#1869 Update test ENV variable descriptions in readme
  README.md
Labels: No Op

#1870 Update README.md
  README.md
Labels: No Op

#1794 Markdown Rendering for Help Pages
  Gemfile
  Gemfile.lock
  app/assets/images/help/probot-settings.gif
  app/assets/images/help/upgrade-organization.png
  app/assets/stylesheets/application.scss
  app/controllers/pages_controller.rb
  app/helpers/markdown_render_helper.rb
  app/views/pages/_back_to_classroom_header.html.erb
  app/views/pages/assistant.html.erb
  app/views/pages/help.html.erb
  app/views/shared/_header.html.erb
  app/views/shared/_invitation_header.html.erb
  config/locales/views/shared/en.yml
  config/routes.rb
  docs/create-group-assignments.md
  docs/help.md
  docs/probot-settings.md
  docs/upgrade-your-organization.md
  package.json
  spec/controllers/pages_controller_spec.rb
  vendor/cache/kramdown-1.17.0.gem
  yarn.lock
Labels: enhancement :sparkles:

#1889 Merge assignment sort and search features
  app/assets/javascripts/roster_tabs.js
  app/assets/javascripts/select_menu.js
  app/assets/stylesheets/components/select_menu.scss
  app/controllers/application_controller/feature_flags_dependency.rb
  app/controllers/assignments_controller.rb
  app/controllers/group_assignments_controller.rb
  app/models/concerns/sortable.rb
  app/models/group_assignment_repo.rb
  app/models/roster_entry.rb
  app/views/assignments/_assignment_roster_list.html.erb
  app/views/assignments/_filterable_assignment_roster_list.html.erb
  app/views/assignments/filter_repos.js.erb
  app/views/assignments/show.html.erb
  app/views/group_assignments/_filterable_group_assignment_repo_list.html.erb
  app/views/group_assignments/_group_assignment_list.html.erb
  app/views/group_assignments/filter_repos.js.erb
  app/views/group_assignments/show.html.erb
  app/views/shared/_select_menu.html.erb
  spec/controllers/assignments_controller_spec.rb
  spec/controllers/group_assignments_controller_spec.rb
  spec/models/group_assignment_repo_spec.rb
  spec/models/roster_entry_spec.rb
  spec/support/cassettes/AssignmentsController/search_for_user_in_the_roster/finds_no_user_if_not_in_roster.json
  spec/support/cassettes/AssignmentsController/search_for_user_in_the_roster/finds_one_user_if_in_roster.json
  spec/support/cassettes/GroupAssignmentRepo/with_created_objects/is_sortable/order_by_sort_mode_sorts_by_Created_at_.json
  spec/support/cassettes/GroupAssignmentRepo/with_created_objects/is_sortable/order_by_sort_mode_sorts_by_Team_name_.json
  spec/support/cassettes/GroupAssignmentsController/search_for_group_assignments/finds_group_assignment_in_search.json
  spec/support/cassettes/GroupAssignmentsController/search_for_group_assignments/finds_no_group_assignment_in_search.json
Labels: assignments :bookmark_tabs:, enhancement :sparkles:

#1904 Make search not case sensitive
  app/controllers/assignments_controller.rb
  app/controllers/organizations_controller.rb
  spec/controllers/assignments_controller_spec.rb
  spec/controllers/organizations_controller_spec.rb
  spec/support/cassettes/AssignmentsController/search_for_user_in_the_roster/search_is_not_case-sensitive.json
  spec/support/cassettes/OrganizationsController/search_organizations/finds_an_organization.json
  spec/support/cassettes/OrganizationsController/search_organizations/finds_no_organization.json
  spec/support/cassettes/OrganizationsController/search_organizations/is_not_case_sensitive.json
Labels: fix :hammer_and_wrench:
